"""Hand-written item specifications for the arrival register.

Read by build_register.py. Every prediction here restates an existing model
in the repository and names its source file. Nothing here is a new theory.
Labels: EVIDENCE (a recorded observation), INFERENCE (this worker's
reasoning), TRADITION, CLAIM. Quotations are 12 words or fewer.
"""

REGISTERED_UTC = "2026-10-09"
AS_OF = "9 October 2026"

# Repository files whose state the predictions rest on. Their SHA-256 is
# written into register.json, so a later change is visible.
SOURCE_FILES = [
    "research/ACTIVE_TEST.md",
    "research/assessments/kohlit_chain/chain.json",
    "research/assessments/kohlit_chain/registration_protocol.md",
    "research/feature_workbench/decisions/discrimination.json",
    "research/feature_workbench/decisions/plans.json",
    "research/feature_workbench/decisions/discriminate.py",
    "research/feature_workbench/coverage/volume_inputs.json",
    "research/feature_workbench/coverage/evaluate.py",
    "research/agent_review_2026-10-07/wave2/W2B_model_v1/registry_v2_entry60.json",
    "research/agent_review_2026-10-07/wave1/T03_T04_registry/XII10_IMAGE_READING_PROTOCOL.md",
    "research/agent_review_2026-10-07/followup/G_saw_gap_xii10.md",
    "research/agent_review_2026-10-07/followup/F_outreach_sent.md",
    "research/text/letter_controls/PROTOCOL.md",
    "research/rarity/kohlit/stage2/addendum_s2/results/unit_results.csv",
    "research/rarity/kohlit/stage1a/stage1a_units.csv",
    "research/rarity/kohlit/observation_process/README.md",
    "research/preregistration/kohlit_rarity_2026-10-08.md",
    "deep_analysis/engraving_order_results.json",
    "research/assessments/entry29_jericho_pools/README.md",
    "research/assessments/entry29_jericho_pools/ac94_pipe_test.md",
    "research/measurements/cycle15/siloam_bathing.md",
    "research/sites/humbert_chambon_1994_dam_access_2026-09-30.md",
    "registration/qumranII2003_extracted.md",
    "research/assessments/entry25_iv17/README.md",
]

# The three chain models whose branches the decision classes already hold.
ROSTER_MODELS = {"M-SULTAN", "M-MARJAMA", "M-JANOAH"}

XII10_TASK = "decisions-xii10"

COVERAGE_LEVELS = {
    1.0: "the item is by definition the record of this relation",
    0.5: "the item was asked for this place or topic; whether it records the relation is unknown",
    0.25: "the relation would be an incidental find in this item",
    0.0: "the item cannot bear on this relation under the frozen rules",
}

XII10_HANDLING = (
    "Reserved observation. No agent opens, crops or views any image of XII 8–12 or of the "
    "21/22 cut. The frozen protocol (fd3f334, SHA-256 0e19467c…) governs: an administrator "
    "records lineage and masks the target; two blinded readers lock Stages 1 and 2. This "
    "register adds no letter prediction. It maps protocol outcomes to model classes only."
)

SULTAN_HANDLING = (
    "Follow research/assessments/kohlit_chain/registration_protocol.md: intake form first, "
    "registration record before any fit, low-resolution preview (5 m per pixel or coarser) "
    "to mark the target strip, controls picked outside the strip, check point withheld. "
    "The SULTAN link predictions below are the step-2 registration that protocol requires."
)

ITEMS = [
    {
        "id": "usc-wsrp-masters-cuts-21-22",
        "title": "WSRP 1988 film masters of cuts 21–22 at 1200 ppi (20 records)",
        "holder": "USC Libraries Special Collections",
        "requested": "8 Oct 2026 about 04:09 UTC (7 Oct Los Angeles)",
        "request_source": "research/ACTIVE_TEST.md (Pending requests); shared status file 8 Oct",
        "request_detail": "Colour UC15246017, UC15246333, UC15245706, UC15246568, UC15246337, UC15246608, UC15246336, UC15246046; colour versos UC15246578, UC15246893; B&W UC15245677, UC15246863, UC15246589, UC15246581, UC15246011, UC15246865, UC15246041, UC15246022, UC15246599, UC15245707.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: the frozen protocol (line 59) lists USC previews, catalogue descriptions and contact sheets as known exposure, and a prior native review of USC cuts 21, 22 and 23 in an entry-49 search. Unused status of any master is therefore unverified until the protocol's audit.",
        ],
        "questions": ["R07"],
        "active_questions": [1],
        "entries": ["60"],
        "reserved": True,
        "handling": XII10_HANDLING,
        "decision_task": XII10_TASK,
        "decision_coverage": 1.0,
        "decision_coverage_reason": "The masters are images of the 21/22 cut by catalogue description.",
        "chain_record_ids": ["REC-XII10-IMAGE"],
        "registry": [
            {"record": "P60-T8", "prediction": "Follows the XII 10 mapping: if R4 (שבינח) is rejected, the RB-L route to Kh. Yanun loses its registered string; if R4 survives, P60-T8 stays open and needs a separate linguistic and geographic argument."},
        ],
        "closed_results": [
            {"result": "Original-photo readings, entries 31/40/49", "reopen": "Legible originals of VII 11, IX 7 or X 15–16 with neighbouring Hebrew and cut placement.", "can_satisfy": "no", "reason": "EVIDENCE: Puech's radiograph captions put columns VII, IX and X on cuts 13–14, 16–17 and 17–18 (letter_controls/controls_manifest.csv). Cuts 21–22 do not hold them. Silent by construction."},
        ],
        "other_predictions": [
            {
                "family": "Letter controls (text/letter_controls/PROTOCOL.md §5)",
                "model": "Series S1 calibration",
                "predicts": "Calibration for series S1 cannot run on these 20 records alone. S1 controls must come from WSRP masters of cuts 1–18 under the same lighting labels, and none were requested.",
                "confirm_if": "The delivery holds only cuts 21–22 frames.",
                "contradict_if": "The delivery also holds masters of cuts 1–18 with matching lighting labels.",
                "inconclusive_if": "Lighting labels are missing, so matching cannot be judged.",
                "silent_if": "Not applicable: the delivery content decides this directly.",
                "label": "INFERENCE from the protocol's series table (deterministic).",
            },
        ],
        "no_prediction": [
            {"family": "Entry 25 classes; IV/17 coverage branches; rarity count; closed Jericho and Siloam branches", "reason": "No registered model in these families uses images of XII 10."},
        ],
    },
    {
        "id": "manchester-museum-allegro",
        "title": "Allegro strip photographs C.21A.1–4, C.22A.1–10, C.21-23.1; photos of the 1955–56 cutting; the 1955 film; Wright Baker drawings; study scans C.10a.1 and C.10.1",
        "holder": "Manchester Museum (John Peel)",
        "requested": "5 Oct 2026 (C.10a.1/C.10.1, rerouted after a bounce); 7 Oct 15:43 UTC (strips 21–23, cutting photos, film, drawings)",
        "request_source": "research/agent_review_2026-10-07/followup/F_outreach_sent.md row 1; research/ACTIVE_TEST.md",
        "request_detail": "Study-resolution scans; photographs of the saw, of segments just after each cut and of loose fragments; study viewing of the 1955 film; drawings or notes by H. Wright Baker. A drafted addendum asking for the backs of segments 21–22 is held, not sent.",
        "status": "pending",
        "status_note": "Reply 8 Oct: checking with the Allegro estate; referred to Joan Taylor. No image received.",
        "arrived_before_registration": [
            {"what": "Native 720-px previews of C.10a.1 and C.10.1 (DQCAAS gallery)", "when": "inspected 5 Oct 2026", "source": "research/phases/phase4_summary.md (Original reconstruction and Allegro mapping follow-up)", "consequence": "Study scans of C.10a.1/C.10.1 are the same photographs at higher resolution: arrived before registration in content, not a test."},
        ],
        "exposure": [
            "EVIDENCE: the frozen protocol (line 59) lists the DQCAAS Allegro low-resolution compositions as known exposure. Study scans of strips 21–23 are the same exposures at higher resolution; per protocol line 61 that is the same observational lineage.",
        ],
        "questions": ["R07", "R11"],
        "active_questions": [1],
        "entries": ["60"],
        "reserved": True,
        "handling": XII10_HANDLING + " Photographs of the cutting and the film may show segments 21/22 before or during cutting: route them to the protocol administrator unopened.",
        "decision_task": XII10_TASK,
        "decision_coverage": 1.0,
        "decision_coverage_reason": "Strips C.21–23 were requested because XII 10 crosses the 21/22 cut.",
        "chain_record_ids": ["REC-XII10-IMAGE"],
        "registry": [
            {"record": "P60-T8", "prediction": "As for the USC masters: follows the XII 10 mapping (R4 rejected → RB-L route loses its string)."},
        ],
        "closed_results": [
            {"result": "R11 Greek engraving order", "reopen": "ACTIVE_TEST: original WSRP Figure 4.6 composite with component IDs and placement map; engraving_order_results.json: a labelled column reconstruction or archival mapping to cut faces.", "can_satisfy": "no", "reason": "C.10a.1/C.10.1 scans are known photographs at higher resolution, not a mapping. They can support exploratory registration only."},
        ],
        "other_predictions": [
            {
                "family": "XII 10 protocol, cut-damaged component rule (protocol line 45)",
                "model": "Frozen protocol fd3f334",
                "predicts": "The letter at the 21/22 cut can become decisive only if an authenticated image made before the cut shows that copper. Strip photographs taken after cutting cannot make it decisive by themselves.",
                "confirm_if": "Not a model claim about letters; recorded as which frames predate the cut (administrator's lineage record).",
                "contradict_if": "Not applicable.",
                "inconclusive_if": "Capture dates of the cutting photographs cannot be established.",
                "silent_if": "No photograph of segment 21/22 before cutting exists in the delivery.",
                "label": "EVIDENCE: protocol text. No letter prediction.",
            },
            {
                "family": "Letter controls (PROTOCOL §5)",
                "model": "Series S2 calibration",
                "predicts": "S2 calibration needs photographs of other strips from the same archive, or original prints of DJD III pls. XLIX–LXVII. Strips 21–23 alone cannot calibrate.",
                "confirm_if": "The delivery holds only strips 21–23 (and C.10).",
                "contradict_if": "The delivery holds other strips under the same lighting.",
                "inconclusive_if": "Lighting of the frames is unrecorded.",
                "silent_if": "Not applicable.",
                "label": "INFERENCE from the protocol's series table.",
            },
        ],
        "no_prediction": [
            {"family": "Entry 25; IV/17 coverage; rarity; closed Jericho and Siloam branches", "reason": "No registered model in these families uses these photographs."},
        ],
    },
    {
        "id": "taylor-dqcaas-allegro-scans",
        "title": "Allegro scans C.21A.1–4, C.22A.1–10, C.22.1–2, C.21-23.1 (side and lighting recorded); any film of segments 21–22; lower priority C.10a.1 and C.10.1",
        "holder": "Joan Taylor, King's College London (DQCAAS orders)",
        "requested": "8 Oct 2026 about 22:00 UTC",
        "request_source": "research/ACTIVE_TEST.md; shared status file 8 Oct",
        "request_detail": "Terms and fees asked first.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [
            {"what": "C.10a.1 and C.10.1 previews", "when": "inspected 5 Oct 2026", "source": "research/phases/phase4_summary.md", "consequence": "Those two scans would not be a test."},
        ],
        "exposure": [
            "INFERENCE: these are the same Allegro photographs as the Manchester Museum request. Whichever copy is read first is the observation; per protocol line 43 a second copy of one exposure adds no second observation.",
        ],
        "questions": ["R07", "R11"],
        "active_questions": [1],
        "entries": ["60"],
        "reserved": True,
        "handling": XII10_HANDLING,
        "decision_task": XII10_TASK,
        "decision_coverage": 1.0,
        "decision_coverage_reason": "Requested specifically for segments 21–22.",
        "chain_record_ids": ["REC-XII10-IMAGE"],
        "registry": [
            {"record": "P60-T8", "prediction": "Follows the XII 10 mapping."},
        ],
        "closed_results": [
            {"result": "R11 Greek engraving order", "reopen": "Figure 4.6 composite with component map, or an archival mapping to cut faces.", "can_satisfy": "no", "reason": "Same as the Manchester Museum C.10 scans."},
        ],
        "other_predictions": [],
        "no_prediction": [
            {"family": "Entry 25; IV/17 coverage; rarity; closed Jericho and Siloam branches", "reason": "No registered model uses these photographs."},
        ],
    },
    {
        "id": "ebaf-edf-copy-and-xrays-21-22",
        "title": "ÉBAF's EDF copy of the scroll and the EDF X-rays of segments 21–22, seen during the 18–24 Oct visit",
        "holder": "École biblique (J.-B. Humbert; visit passed to Fr. Cyrille Jalabert)",
        "requested": "8 Oct 2026 about 04:22 UTC",
        "request_source": "research/ACTIVE_TEST.md; shared status file 8 Oct",
        "request_detail": "To see the copy and the X-rays during the visit.",
        "status": "pending",
        "status_note": "Reply 8 Oct: visit passed to Fr. Jalabert. Viewing expected 18–24 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: the protocol lists Puech's copy, photo and radiograph plates as known exposure (pls. CCCLV–CCCLVI show the cut). Whether the EDF films are those exposures is unknown: unused status unverified.",
            "INFERENCE: the owner, if he views the X-rays himself, becomes exposed and cannot serve as a blinded reader. Record his viewing scope.",
        ],
        "questions": ["R07"],
        "active_questions": [1],
        "entries": ["60"],
        "reserved": True,
        "handling": XII10_HANDLING + " On site: record film or copy identifiers, capture conditions and any photographs made, before anyone reads the target.",
        "decision_task": XII10_TASK,
        "decision_coverage": 1.0,
        "decision_coverage_reason": "The X-rays are radiographs of segments 21–22. The copy part gets no decisive rows (see other predictions).",
        "chain_record_ids": ["REC-XII10-IMAGE"],
        "registry": [
            {"record": "P60-T8", "prediction": "Follows the XII 10 mapping."},
        ],
        "closed_results": [],
        "other_predictions": [
            {
                "family": "XII 10 protocol, evidence rule (protocol lines 37 and 43)",
                "model": "Frozen protocol fd3f334",
                "predicts": "Observations on the EDF copy cannot be decisive letter components, because a decisive mark must be visible in the unadjusted original. They are reported separately (letter controls series S4).",
                "confirm_if": "Not a letter claim; the copy is logged as series S4.",
                "contradict_if": "Not applicable.",
                "inconclusive_if": "Not applicable.",
                "silent_if": "The copy is not shown.",
                "label": "INFERENCE from protocol wording; the integrator should confirm that a galvanoplastic copy counts as a copy, not the original.",
            },
            {
                "family": "Letter controls (PROTOCOL §5)",
                "model": "Series S3 calibration",
                "predicts": "S3 calibration needs EDF radiographs of segments 1–18. X-rays of 21–22 alone cannot calibrate.",
                "confirm_if": "Only 21–22 radiographs are seen or copied.",
                "contradict_if": "Radiographs of segments 1–18 are also obtained.",
                "inconclusive_if": "Segment identities of the films are unrecorded.",
                "silent_if": "No radiograph is shown.",
                "label": "INFERENCE from the protocol's series table.",
            },
        ],
        "no_prediction": [
            {"family": "Entry 25; IV/17 coverage; rarity; closed Jericho and Siloam branches", "reason": "No registered model uses these images."},
        ],
    },
    {
        "id": "uml-tpa-1-132-wright-baker",
        "title": "File GB 133 TPA/1/132 (Allegro–Harding–Wright Baker letters on the cutting) and other Wright Baker records",
        "holder": "University of Manchester Library, Special Collections",
        "requested": "7 Oct 2026 15:43 UTC",
        "request_source": "research/agent_review_2026-10-07/followup/F_outreach_sent.md row 2",
        "request_detail": "Whether the file holds or mentions photographs, negatives, drawings, measurements or reports of the cuts; Faculty of Science (GB 133 FSC) and UMIST records; any Allegro papers.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Wright Baker's published account (BJRL 39.1, 1956, pp. 45–56) is already read in G_saw_gap_xii10.md. Statements in the file by the same author are the same lineage.",
        ],
        "questions": ["R07", "R11"],
        "active_questions": [1],
        "entries": ["60"],
        "reserved": True,
        "handling": "Correspondence may be read by any worker. Any photograph, negative or drawing that shows text near segments 21/22 goes to the XII 10 protocol administrator unopened.",
        "decision_task": XII10_TASK,
        "decision_coverage": 0.25,
        "decision_coverage_reason": "Only if the file holds photographs of segment 21/22 made before the cut (protocol line 45). Correspondence is the expected content.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [
            {"result": "R11 Greek engraving order", "reopen": "engraving_order_results.json: labelled column reconstruction or archival mapping linking edition line ends to cut faces.", "can_satisfy": "partly", "reason": "INFERENCE: a 1955–56 record of which text lies on which segment would be such a mapping for the cut side; it would not supply the Figure 4.6 component map named in ACTIVE_TEST."},
        ],
        "other_predictions": [
            {
                "family": "Saw-gap check (followup/G_saw_gap_xii10.md)",
                "model": "Result 1: a whole letter cannot have been lost in the cut",
                "predicts": "Any blade or kerf figure in the file agrees with 0.006 in (0.152 mm), and no record gives a kerf or edge loss at 21/22 of 1 mm or more.",
                "confirm_if": "A recorded blade or kerf of 0.25 mm or less.",
                "contradict_if": "A recorded kerf or edge loss at cut 21/22 of 1 mm or more (the size G says would be needed to lose a whole letter).",
                "inconclusive_if": "Figures given for the saw in general but not for cut 21/22, or units unclear.",
                "silent_if": "The file gives no saw or cut measurements.",
                "label": "EVIDENCE for the 0.006 in figure (BJRL p. 50); thresholds from G's stated letter sizes.",
            },
            {
                "family": "Edition placement of the 21/22 cut (W2A, as cited in G)",
                "model": "Editions place cut 21/22 through the last letter of word 2 of XII 10",
                "predicts": "A cutting record that marks cut positions places cut 21/22 within word 2 of XII 10, not between words.",
                "confirm_if": "A written statement or diagram key places the cut in word 2.",
                "contradict_if": "A record places cut 21/22 in another line position or between words. This questions the 21/22 target hypothesis, which the protocol already treats as a hypothesis.",
                "inconclusive_if": "Cut positions are given by segment only.",
                "silent_if": "No cut-position record.",
                "label": "EVIDENCE (editions, recorded in W2A). No letter identity is predicted. A diagram showing letters is routed to the administrator.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit chain models; entry 25; IV/17; rarity; closed Jericho and Siloam branches", "reason": "No registered model uses cutting records."},
        ],
    },
    {
        "id": "hogenhaven-independent-readings",
        "title": "Independent reading of X 15, VII 11, IX 7 and XII 10",
        "holder": "J. Høgenhaven",
        "requested": "29 Sept 2026 15:32 UTC",
        "request_source": "registration/outreach_replies_2026-09-29.md; research/ACTIVE_TEST.md",
        "request_detail": "A reading of four disputed lines.",
        "status": "pending",
        "status_note": "No reply found on 29 and 30 Sept; none recorded since.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: the request named the four lines and called them disputed. The reader is therefore not blinded to the dispute.",
        ],
        "questions": ["R07", "R04", "R06"],
        "active_questions": [1],
        "entries": ["60", "31", "40", "49"],
        "reserved": True,
        "handling": "A written reading is text, not an image, and any worker may read it after this register is pushed. If the reply attaches images of XII 8–12, route them to the protocol administrator unopened.",
        "decision_task": XII10_TASK,
        "decision_coverage": 0.0,
        "decision_coverage_reason": "One reader, not blinded, outside the protocol's two-reader design: under protocol outcome 3 the result is 'not identifiable'. No class can be excluded.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [
            {"result": "Original-photo readings, entries 31/40/49", "reopen": "Legible originals of VII 11, IX 7 or X 15–16 with neighbouring Hebrew and cut placement.", "can_satisfy": "no", "reason": "A reading is not an original image. It is recorded as an exploratory expert opinion."},
        ],
        "other_predictions": [
            {
                "family": "XII 10 protocol (outcome 3)",
                "model": "Frozen protocol fd3f334",
                "predicts": "Whatever letters the reading gives, the protocol outcome for XII 10 is 'not identifiable from available evidence', and all 10 Koḥlit classes and all 7 strings survive.",
                "confirm_if": "The reply is a single reading without the protocol's blinded two-reader record.",
                "contradict_if": "Not applicable (deterministic under the protocol).",
                "inconclusive_if": "Not applicable.",
                "silent_if": "No reply.",
                "label": "EVIDENCE: protocol lines 39–43 and 53.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit chain models other than via XII 10; entry 25; IV/17; rarity", "reason": "No registered model uses an expert reading."},
        ],
    },
    {
        "id": "garstang-museum-jg8",
        "title": "Garstang Jericho papers JG/8; pre-camp photographs and plans of the ground north of Tell es-Sultan",
        "holder": "Garstang Museum of Archaeology, University of Liverpool",
        "requested": "8 Oct 2026 about 04:09 UTC",
        "request_source": "research/ACTIVE_TEST.md; registration_protocol.md §1",
        "request_detail": "Papers and pre-1948 records of the strip north of the tell.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: no Garstang record has been inspected in the repository (git grep finds only request mentions).",
        ],
        "questions": ["R07"],
        "active_questions": [2],
        "entries": ["60", "19", "11"],
        "reserved": False,
        "handling": SULTAN_HANDLING,
        "decision_task": None,
        "decision_none_reason": "decisions/discrimination.json, supplementary observation 'north-strip pit mouth': a newly recorded pit in the strip is a new feature assignment, not one of the registered pit roles, so it separates no registered Koḥlit class.",
        "chain_record_ids": ["REC-GARSTANG-LIV"],
        "chain_coverage": {"default": 0.5},
        "registry": [
            {"record": "P60-T1", "prediction": "Its confirm rule needs an independently dated pit and mouth–tomb relation. Photographs and plans locate but do not date (registration_protocol §6). Predicted: P60-T1 stays 'not identifiable' whatever these records show, unless they include a sealed, dated context."},
        ],
        "coverage_cases": [
            {"case": "coverage-volume-tell-es-sultan", "prediction": "All 4 joins stay undeterminable. Entry 60 states no distance, so the target needs a declared distance band, which no field record can supply (volume_inputs.json declarations)."},
        ],
        "closed_results": [],
        "other_predictions": [
            {
                "family": "SULTAN-5-basin-corner (chain.json)",
                "model": "Tell es-Sultan, all branches using the historical basin",
                "predicts": "Silent by construction for records made in 1930–36: the link needs a record made before the 1891–93 mill works.",
                "confirm_if": "Only a pre-1891 record in the papers showing an angle on the basin's north side.",
                "contradict_if": "None from photographs (one-sided).",
                "inconclusive_if": "A pre-1891 record that does not show the north side.",
                "silent_if": "No record older than 1891 (expected).",
                "label": "EVIDENCE: chain.json link text.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit decision classes; XII 10 strings; entry 25; rarity", "reason": "See decision_none_reason; no other family uses this ground."},
        ],
    },
    {
        "id": "pef-garstang-papers-jericho-photos",
        "title": "Garstang Papers 1930–36 and pre-1948 photographs of Jericho",
        "holder": "Palestine Exploration Fund, London",
        "requested": "8 Oct 2026 about 04:09 UTC",
        "request_source": "research/ACTIVE_TEST.md; registration_protocol.md §1",
        "request_detail": "Papers and photographs; pre-1948 views of the ground north of the tell and of the spring.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Dorrell 1993 Figs 1–4 and 20–21 are already inspected; many early spring photographs are in Dorrell's selection. Only PEF records outside Dorrell's selection count for SULTAN-5 (chain.json note).",
        ],
        "questions": ["R07"],
        "active_questions": [2, 3],
        "entries": ["60", "19", "11"],
        "reserved": False,
        "handling": SULTAN_HANDLING + " Before opening, list which photographs are already in Dorrell 1993; mark them exposed.",
        "decision_task": None,
        "decision_none_reason": "Same as the Garstang Museum item: a new strip pit is not a registered pit role. A spring photograph cannot supply the sealed basin-rim contact the decisions module needs (supplementary observation 'springhouse sealed finds').",
        "chain_record_ids": ["REC-PEF"],
        "chain_coverage": {"default": 0.5},
        "registry": [
            {"record": "P60-T1", "prediction": "As for the Garstang Museum item: stays 'not identifiable' unless a dated sealed context is recorded."},
        ],
        "coverage_cases": [
            {"case": "coverage-volume-tell-es-sultan", "prediction": "All 4 joins stay undeterminable (no distance band can come from a record)."},
        ],
        "closed_results": [],
        "other_predictions": [],
        "no_prediction": [
            {"family": "Koḥlit decision classes; XII 10 strings; entry 25; rarity", "reason": "No registered class uses these records."},
        ],
    },
    {
        "id": "nigro-north-strip-records",
        "title": "Records of the ground north of Tell es-Sultan; dating of karstic cavities there",
        "holder": "Lorenzo Nigro, Sapienza University of Rome (Jericho expedition)",
        "requested": "8 Oct 2026 about 04:09 UTC; meeting proposed 8 Oct 04:22 UTC for 18–24 Oct",
        "request_source": "research/ACTIVE_TEST.md; shared status file 8 Oct",
        "request_detail": "Records of the strip; he will check whether any cavity dates to the scroll's period.",
        "status": "partial",
        "status_note": "Reply received 8 Oct (content below). Records not received.",
        "arrived_before_registration": [
            {"what": "Reply: karstic cavities are common in the strip; their date is the open question and he will check", "when": "8 Oct 2026", "source": "research/ACTIVE_TEST.md; shared status file", "consequence": "That openings exist in the strip is known before registration: not a test. Only the grave-within-10-m relation and any feature date remain unseen."},
        ],
        "exposure": [
            "EVIDENCE: Nigro, Sala and Taha 2011 (ROSAPAT 07) is already inspected (chain record REC-NIGRO-2011).",
        ],
        "questions": ["R07"],
        "active_questions": [2],
        "entries": ["60"],
        "reserved": False,
        "handling": SULTAN_HANDLING + " A spoken answer at the meeting is logged in writing the same day, with what was shown.",
        "decision_task": None,
        "decision_none_reason": "A dated cavity in the strip would be a new feature assignment; it separates no registered class until added to the relationships roster (decisions supplementary observation).",
        "chain_record_ids": ["REC-NIGRO-RECORDS"],
        "chain_coverage": {"default": 0.5},
        "registry": [
            {"record": "P60-T1", "prediction": "Period requirement: a cavity shown open within 50 BCE–70 CE (extended to 135 CE) with graves within 10 m satisfies the period and mouth parts for that feature only. A cavity securely built after 135 CE is a MISS for that feature only. Undated cavities leave P60-T1 'not identifiable'. No reply about dating is a FAIL of nothing."},
        ],
        "coverage_cases": [
            {"case": "coverage-volume-tell-es-sultan", "prediction": "All 4 joins stay undeterminable."},
        ],
        "closed_results": [],
        "other_predictions": [],
        "no_prediction": [
            {"family": "Koḥlit decision classes; XII 10 strings; entry 25; rarity", "reason": "No registered class uses these records."},
        ],
    },
    {
        "id": "ebaf-qumran-volumes-1-2",
        "title": "Gift copies of the ÉBAF Qumran volumes I–II",
        "holder": "École biblique (Fr. Cyrille Jalabert)",
        "requested": "Offered 8 Oct 2026, with the visit",
        "request_source": "research/ACTIVE_TEST.md; shared status file 8 Oct",
        "request_detail": "INFERENCE: vol. I = Humbert and Chambon 1994, Fouilles de Khirbet Qumrân et de Aïn Feshkha I; vol. II = Humbert and Gunneweg 2003. Record the actual title pages on receipt; if they differ, log them verbatim.",
        "status": "pending",
        "status_note": "Hand-over expected during the 18–24 Oct visit.",
        "arrived_before_registration": [
            {"what": "Volume II (Humbert and Gunneweg 2003)", "when": "reviewed 28 Sept 2026 from a user attachment", "source": "registration/qumranII2003_extracted.md", "consequence": "Arrived before registration: not a test."},
            {"what": "Volume IIIA (Humbert, Chambon and Młynarczyk 2016), if handed over", "when": "already in the owner's Drive", "source": "research/sources/drive_index.md", "consequence": "Not a test."},
        ],
        "exposure": [
            "EVIDENCE: Galor (vol. II p. 318 n. 7) cites Humbert–Chambon 1994 pp. 192 and 342 for the dam; those pages are unread (sites/humbert_chambon_1994_dam_access_2026-09-30.md).",
        ],
        "questions": ["R01", "R07"],
        "active_questions": [],
        "entries": ["20", "21", "22", "23", "60"],
        "reserved": False,
        "handling": "Ordinary source intake. Read vol. I pp. 192, 195–199 and 342 only after this register is pushed.",
        "decision_task": None,
        "decision_none_reason": "No decision task concerns Qumran.",
        "chain_record_ids": [],
        "extra_links": [
            {"model": "M-QUMRAN", "link": "QUMRAN-2-mouth", "coverage": 0.25, "note": "INFERENCE: vol. I synthesises de Vaux's field notes and photographs, which may show the northern cemetery and openings beside it. The chain does not list this record."},
        ],
        "registry": [
            {"record": "P60-T7", "prediction": "No prediction: P60-T7 (ʿAyn Feshkha area) has no next test ('None before T1–T3')."},
        ],
        "closed_results": [],
        "other_predictions": [
            {
                "family": "Referent of Humbert's gorge dam (sites/humbert_chambon_1994_dam_access_2026-09-30.md)",
                "model": "A: Ilan–Amit point 4 (a proposed dam across basin 2 in the main wadi; no surviving wall reported)",
                "predicts": "Vol. I pp. 192/342 describe or draw the dam at the aqueduct head in the upper gorge, as a reconstruction or traces.",
                "confirm_if": "The plan, registered to Ilan–Amit's numbered plan, puts the dam at point 4.",
                "contradict_if": "The plan puts an observed masonry wall at point 19 or at the pothole, and nothing at point 4.",
                "inconclusive_if": "No plan, or a plan that cannot be registered to the numbered points.",
                "silent_if": "The pages do not concern the dam.",
                "label": "EVIDENCE for the alternatives; the page content is unseen.",
            },
            {
                "family": "Referent of Humbert's gorge dam",
                "model": "B: Ilan–Amit point 19 (a downstream wall at the final turn toward the settlement)",
                "predicts": "The described dam is the wall at the final turn.",
                "confirm_if": "The registered plan puts it at point 19.",
                "contradict_if": "The registered plan puts it upstream (point 4 or the pothole wall).",
                "inconclusive_if": "Unregistrable plan or text-only description.",
                "silent_if": "Pages not about the dam.",
                "label": "EVIDENCE for the alternative.",
            },
            {
                "family": "Referent of Humbert's gorge dam",
                "model": "C: the Reeder–Jol wall above the pothole",
                "predicts": "The described dam is an observed wall above the pothole.",
                "confirm_if": "The registered plan or a photograph puts it above the pothole.",
                "contradict_if": "The registered plan puts it at point 4 or 19 only.",
                "inconclusive_if": "No registrable plan.",
                "silent_if": "Pages not about the dam.",
                "label": "EVIDENCE for the alternative.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit decision classes; XII 10; entry 25; IV/17; rarity; closed tests", "reason": "No registered class uses these volumes."},
        ],
    },
    {
        "id": "mosaic-centre-meinardus-scan",
        "title": "Scan of Meinardus, 'The Byzantine Church of St. Andrew in Jericho', BSAC XVIII (1965–66) pp. 181–196, with plan and plates",
        "holder": "Mosaic Centre Jericho (Carla Benelli; Osama Hamdan Archive)",
        "requested": "Offered 7 Oct 2026; visit request 8 Oct about 04:22 UTC",
        "request_source": "research/ACTIVE_TEST.md; research/assessments/entry29_jericho_pools/README.md (Meinardus scan specification)",
        "request_detail": "Scan expected mid-October, free of charge. Most useful pages: 182–185 and 196, all 14 plates with captions.",
        "status": "pending",
        "status_note": "Reply 7 Oct: will scan in mid-October. Archive visit welcome except Friday and Thursday afternoon.",
        "arrived_before_registration": [
            {"what": "User-reported Google Books snippets of pp. 181–182, 186, 188–190, 193–194; derivative citations (PADIS, a Chicago dissertation) of pp. 183–184 for a Herodian pool, cisterns and jars", "when": "6 Oct 2026", "source": "research/assessments/entry29_jericho_pools/README.md (Meinardus scan sources)", "consequence": "Those pages and the derivative Herodian attribution are exposed: confirming them is not a test. Only pp. 183–185, 195–196 and the plates are unseen."},
        ],
        "exposure": [],
        "questions": ["R07", "R09"],
        "active_questions": [],
        "entries": ["29"],
        "reserved": False,
        "handling": "Ordinary source intake under the plans/assets workflow. Record page images' hashes, not the images, unless reuse is permitted.",
        "decision_task": None,
        "decision_none_reason": "The St Andrew reservoir (J19) is not a modelled branch in the decisions module.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [
            {"result": "Jericho pools, entry 29 (St Andrew reservoir, J19)", "reopen": "Meinardus pp. 183–184 and 196 with the plan key and captions.", "can_satisfy": "yes", "reason": "The scan is the named reopening record. Reopening means re-evaluation; the result may stay 'not identifiable'."},
        ],
        "other_predictions": [
            {
                "family": "J19 gates (entry29_jericho_pools/README.md)",
                "model": "J19-a: Herodian construction (derivative attribution to pp. 183–184)",
                "predicts": "Pp. 183–184 date the pool, cisterns and jars to the Herodian or Roman period, on a stated basis.",
                "confirm_if": "A dated construction or use contact for the pool itself (sealed finds, a joint with a dated wall).",
                "contradict_if": "Meinardus dates the pool's construction to the church phase (sixth–seventh century) or later.",
                "inconclusive_if": "A period label without a feature-specific basis (the expected derivative-type statement).",
                "silent_if": "Pp. 183–184 do not concern the pool.",
                "label": "EVIDENCE for the derivative attribution; basis unseen.",
            },
            {
                "family": "J19 gates",
                "model": "J19-b: earlier construction with later monastic use",
                "predicts": "The pool is described as earlier than the church and reused with it.",
                "confirm_if": "Text or plan shows a physical tie between the pool and the monastic rooms, with the pool earlier.",
                "contradict_if": "The pool is shown built with or after the church fabric.",
                "inconclusive_if": "No relation between pool and church fabric is described.",
                "silent_if": "No pool description.",
                "label": "EVIDENCE: alternative recorded in the J19 notes.",
            },
            {
                "family": "J19 gates",
                "model": "J19-c: Meinardus's pool is a separate feature from CMHL's nearby plastered reservoir",
                "predicts": "The plan (p. 196) places Meinardus's pool or fishpond away from the reservoir that CMHL describes.",
                "confirm_if": "Plan positions and dimensions differ from CMHL's reservoir.",
                "contradict_if": "Plan and dimensions match CMHL's reservoir.",
                "inconclusive_if": "No plan key or no dimensions.",
                "silent_if": "No plan in the scan.",
                "label": "EVIDENCE: alternative recorded in the J19 notes.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit; XII 10; entry 25; IV/17; rarity", "reason": "No registered class uses this article."},
        ],
    },
    {
        "id": "iaa-archive-cave-records",
        "title": "Judean Desert cave-survey records: Qumran cliffs and marl, Jericho escarpment (Jebel Qarantal to Wadi Nuweiʿimeh/ʿAin Duk), Wadi Qelt gorge",
        "holder": "Israel Antiquities Authority Archive (to forward to the Judean Desert survey project)",
        "requested": "7 Oct 2026 15:43 UTC",
        "request_source": "research/agent_review_2026-10-07/followup/F_outreach_sent.md row 3",
        "request_detail": "Per cave: identifier, coarse location (100–250 m cell), number of openings and their facing, features, size, periods, disturbance.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: the 2002 cave-survey entries cited by WBADB are supplied but unread for these caves (chain record REC-ATIQOT41-CAVES). INFERENCE: they are the same survey lineage. Whichever is opened first is the observation; these predictions apply to both.",
            "EVIDENCE: IV/17 (Sion 2002 Plan 5) is already inspected; its chord-normal proxies are 123° and 119° (entry25_iv17/README.md).",
        ],
        "questions": ["R07", "R02"],
        "active_questions": [],
        "entries": ["60", "25"],
        "reserved": False,
        "handling": "Ordinary intake. Before reading facing fields, check that this register is pushed.",
        "decision_task": None,
        "decision_none_reason": "No decision task uses the cave inventory. Entry 25 mouth bearings could separate classes, but no aspect rule is frozen (decisions README), so this item gets no Entry 25 rows (RANKING_PLAN).",
        "chain_record_ids": ["REC-IAA-CAVES"],
        "chain_coverage": {"default": 0.25, "opening-facing": 0.5},
        "registry": [
            {"record": "P60-T4", "prediction": "No prediction: next test 'None'."},
            {"record": "P60-T7", "prediction": "No prediction: next test 'None before T1–T3'."},
        ],
        "closed_results": [],
        "other_predictions": [
            {
                "family": "Entry 25 (decisions iv17 task, bearing component)",
                "model": "Classes needing both mouths east (entry25-c02, c03, c05)",
                "predicts": "No scoreable prediction: no aspect rule is frozen. A per-mouth facing for IV/17 is logged as data only.",
                "confirm_if": "Not scoreable.",
                "contradict_if": "Not scoreable.",
                "inconclusive_if": "Always, until an aspect rule is frozen before the record is read.",
                "silent_if": "No per-mouth facing for IV/17.",
                "label": "INFERENCE. Proposal: the integrator freezes an aspect rule before this item or the L-656 file arrives.",
            },
        ],
        "no_prediction": [
            {"family": "XII 10 strings; IV/17 coverage; rarity counts; closed tests", "reason": "No registered model uses a cave inventory; no model predicts how many two-mouth caves the region holds (R02 regional eligibility)."},
        ],
    },
    {
        "id": "zuckerman-wsrp-fig-4-6",
        "title": "Original WSRP Figure 4.6 composite (cuts 5 and 6 joined into column II) with component-image IDs and placement map",
        "holder": "Bruce Zuckerman, USC West Semitic Research Project",
        "requested": "5 Oct 2026",
        "request_source": "research/ACTIVE_TEST.md; research/phases/phase4_summary.md",
        "request_detail": "High-resolution composite and its component map or masks.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [
            {"what": "Published Figure 4.6 (CSS p. 52), native 152 × 259 px", "when": "inspected 5 Oct 2026", "source": "research/phases/phase4_summary.md", "consequence": "The low-resolution composite is exposed; only the component IDs and placement map are new."},
        ],
        "exposure": [],
        "questions": ["R11"],
        "active_questions": [],
        "entries": [],
        "reserved": False,
        "handling": "Ordinary intake. Column II only; no XII image is involved.",
        "decision_task": None,
        "decision_none_reason": "R11 is not a decisions family.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [
            {"result": "R11 Greek engraving order", "reopen": "The original WSRP Figure 4.6 composite with component-image IDs and placement map.", "can_satisfy": "yes", "reason": "It is the named reopening record."},
        ],
        "other_predictions": [
            {
                "family": "R11 frozen protocol (deep_analysis/engraving_order_protocol.json, d7d3b60)",
                "model": "All four surviving alternatives (same session; later episode; different hand or tool; relief altered)",
                "predicts": "The map can register loci II2 ΗΝ, II4 ΘΕ/ΞΕ and II9 ΔΙ to raw frames, but alone it separates none of the four. The terminal rule needs an authenticated crossing seen under two light directions by two readers; a later episode also needs an independent intervening event.",
                "confirm_if": "R11 stays 'not identifiable' after the map is applied, with the three loci registered or not.",
                "contradict_if": "The map itself carries an authenticated crossing with documented lighting (not expected from a composite).",
                "inconclusive_if": "The map arrives without component IDs.",
                "silent_if": "No map.",
                "label": "EVIDENCE: protocol terminal rule and episode criterion.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit; XII 10; entry 25; IV/17; rarity", "reason": "Column II engraving order bears on none of them."},
        ],
    },
    {
        "id": "szanton-siloam-l103-section",
        "title": "Siloam main-side L103 junction section (surveyed main-basin conduit/trough junction)",
        "holder": "Nahshon Szanton, Tel Aviv University",
        "requested": "6 Oct 2026 05:29:46 UTC",
        "request_source": "research/measurements/cycle15/siloam_bathing.md (request sent)",
        "request_detail": "A named, phase-controlled main-basin junction or section with datum definitions, or the excavation limits, or a custodian referral.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Szanton–Vukosavović–Berko 2024 pp. 27*–39* and Greenhut–Mazor 2020 are already inspected; plans published there are not new.",
        ],
        "questions": ["R06"],
        "active_questions": [],
        "entries": ["49"],
        "reserved": False,
        "handling": "Ordinary intake.",
        "decision_task": "decisions-siloam-main-side",
        "decision_coverage": 1.0,
        "decision_coverage_reason": "The section is the requested record of the junction.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [
            {"result": "Siloam main pool, entry 49", "reopen": "A surveyed section of the main-side L103 junction with aperture, basin edge and floor in one phase, plus evidence for the bath function.", "can_satisfy": "partly", "reason": "The section can supply the junction; the bath-function evidence is a separate requirement."},
        ],
        "other_predictions": [
            {
                "family": "Siloam named branch (decisions entry49-siloam-c01)",
                "model": "Main-basin branch: Birket al-Hamra is the bathing pool; the place lies under a pipe inside it",
                "predicts": "A surveyed under-pipe place inside the main basin, with basin boundary, ancient floor and the terminal in one phase.",
                "confirm_if": "Outcome main-place-established.",
                "contradict_if": "Outcome terminal-or-phase-miss: the named terminal lies outside the basin or outside the required phase.",
                "inconclusive_if": "Outcome unexposed-junction (the junction was never exposed).",
                "silent_if": "Outcome reply-or-record-inconclusive.",
                "label": "EVIDENCE: plans.json outcomes.",
            },
            {
                "family": "Siloam, receiver alternative (siloam_bathing.md)",
                "model": "L103 connects to the small receiving basin, not to a place inside Birket",
                "predicts": "The section shows the junction at the receiver side, with no main-basin under-pipe place.",
                "confirm_if": "The junction is drawn at the receiver.",
                "contradict_if": "A main-basin junction is drawn in the same phase.",
                "inconclusive_if": "Junction unexposed.",
                "silent_if": "No section.",
                "label": "EVIDENCE: recorded plan topology.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit; XII 10; entry 25; IV/17; rarity", "reason": "Unrelated entry."},
        ],
    },
    {
        "id": "barnathan-porat-ac94-junction",
        "title": "A(C)94 early-pipe wall-junction drawing and level register",
        "holder": "Rachel Bar-Nathan and Roi Porat (referred by Ruhama Bonfil)",
        "requested": "6 Oct 2026 13:54 UTC",
        "request_source": "research/assessments/entry29_jericho_pools/netzer2001-first-pass.md (Ruhama reply and archive referrals)",
        "request_detail": "Who holds the field drawings and level register; a scaled wall-junction section and field-item ID; definitions of 102.87/102.80 and bench 102.73; face, surface and phase records.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct. Ruhama Bonfil's unit holds none of the records (6 Oct).",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Netzer 2001 Plan 13 and pp. 51–60, 67–69 are already inspected; the plan-trace distances are known.",
        ],
        "questions": ["R08", "R09"],
        "active_questions": [],
        "entries": ["29"],
        "reserved": False,
        "handling": "Ordinary intake. Before measuring, freeze the aperture point definition and the face (A(C)94 first), as AGENTS.md requires for a reopened branch.",
        "decision_task": "decisions-jericho-contacts",
        "decision_coverage": 1.0,
        "decision_coverage_reason": "The drawing and register are the requested record of the junction.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [
            {"result": "Jericho pools, entry 29 (A(C)94)", "reopen": "A phase-controlled field section tying a water aperture to a named wall face and its contemporaneous floor.", "can_satisfy": "yes", "reason": "It is the named reopening record if it carries phase control."},
        ],
        "other_predictions": [
            {
                "family": "A(C)94 geometry models (ac94_pipe_test.md; readings 24 or 27 cubits at 0.40–0.60 m)",
                "model": "East-face models (inner and outer contours)",
                "predicts": "The defined aperture lies 9.6–14.4 m (24 cubits) or 10.8–16.2 m (27 cubits) from the named east face, by shortest distance. The drawn terminus gives 7.93–8.38 m, so these models need the aperture upstream of the drawn terminus or a face elsewhere.",
                "confirm_if": "Measured shortest distance inside a band, with face and aperture in one phase.",
                "contradict_if": "Measured shortest distance outside both bands under both face contours, in one phase.",
                "inconclusive_if": "Levels without a datum, or point definitions still unknown.",
                "silent_if": "No metric record.",
                "label": "EVIDENCE: bands and plan-trace values from ac94_pipe_test.md.",
            },
            {
                "family": "A(C)94 geometry models",
                "model": "West-face models",
                "predicts": "They need 9.6 m or more; the plan gives 0.96–3.87 m. They are predicted to miss again unless the aperture is not where the plan draws it.",
                "confirm_if": "An aperture at 9.6 m or more from the west face.",
                "contradict_if": "The aperture is at the north short side near the north-west corner, as published.",
                "inconclusive_if": "Aperture position undefined.",
                "silent_if": "No metric record.",
                "label": "EVIDENCE: ac94_pipe_test.md results.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit; XII 10; entry 25; IV/17; rarity", "reason": "Unrelated entry."},
        ],
    },
    {
        "id": "soa-wadi-nueima-file",
        "title": "Wadi Nuʿeima inspection file behind ESI 5 pp. 110–111",
        "holder": "Archaeology Unit, Staff Officer for Archaeology (Judea and Samaria)",
        "requested": "6 Oct 2026 14:17:38 UTC",
        "request_source": "research/assessments/entry29_jericho_pools/wadi_en_nueima_original_2026-10-06.md (archive referral sent)",
        "request_detail": "The inspection file, bath drawing and accession.",
        "status": "pending",
        "status_note": "No reply recorded by 9 Oct.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Dinur–Feig, ESI 5 pp. 110–111 is fully inspected: one miqva about 1.3 m deep about 2 m north of the wadi, and a separate western rectangle.",
            "EVIDENCE: Sion 2002 p. 82 names this archive as the holder of the IV/17 permit L-656 file. The request did not ask for it.",
        ],
        "questions": ["R07", "R08", "R09"],
        "active_questions": [],
        "entries": ["29"],
        "reserved": False,
        "handling": "Ordinary intake. Note any statement about the L-656 file's custody separately; it is custody information, not a test.",
        "decision_task": "decisions-wadi-bath-contact",
        "decision_coverage": 0.5,
        "decision_coverage_reason": "The request is for the inspection file; whether it holds a bath plan or section is unknown.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [
            {"result": "Jericho pools, entry 29 (Wadi Nuʿeima)", "reopen": "A phase-controlled field section tying a water aperture to a named wall face and its contemporaneous floor.", "can_satisfy": "yes", "reason": "If the file holds the bath drawing with contacts."},
        ],
        "other_predictions": [
            {
                "family": "Wadi named branch (decisions entry29-wadi-c01)",
                "model": "The individually identified bath has a dated water aperture, wall and floor contact in one usable state",
                "predicts": "The file holds a bath plan or section with a water aperture tied to a wall and a contemporaneous floor.",
                "confirm_if": "Outcome dated-water-contact.",
                "contradict_if": "Outcome state-contact-miss.",
                "inconclusive_if": "Outcome identity-without-contact.",
                "silent_if": "Outcome file-lost-or-unobtained.",
                "label": "EVIDENCE: plans.json outcomes.",
            },
            {
                "family": "Custody of the L-656 file",
                "model": "None (custody fact)",
                "predicts": "Silent on L-656: it was not requested.",
                "confirm_if": "Not applicable.",
                "contradict_if": "Not applicable.",
                "inconclusive_if": "Not applicable.",
                "silent_if": "Expected.",
                "label": "INFERENCE.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit; XII 10; entry 25 classes; rarity", "reason": "Unrelated record."},
        ],
    },
    {
        "id": "reeder-jol-qumran-gpr",
        "title": "2002 Qumran aqueduct survey and GPR records",
        "holder": "P. Reeder and H. Jol",
        "requested": "29 Sept 2026 15:32 UTC",
        "request_source": "registration/outreach_replies_2026-09-29.md; research/ACTIVE_TEST.md",
        "request_detail": "Original survey data (historical question Q38).",
        "status": "pending",
        "status_note": "No reply found on 29 Sept; none recorded since.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: de Vaux's pool layout is already inspected, so the chain link QUMRAN-3 is exploratory, not an unseen test (chain.json note).",
            "INFERENCE (wave1 T09 report): GPR performs poorly in saline marl.",
        ],
        "questions": ["R01", "R07"],
        "active_questions": [],
        "entries": ["20", "21", "60", "11"],
        "reserved": False,
        "handling": "Ordinary intake.",
        "decision_task": None,
        "decision_none_reason": "No decision task concerns Qumran.",
        "chain_record_ids": ["REC-REEDER-JOL"],
        "chain_coverage": {"default": 0.25},
        "registry": [],
        "closed_results": [],
        "other_predictions": [
            {
                "family": "Referent of the wall above the pothole (sites/humbert_chambon_1994_dam_access_2026-09-30.md; Q38)",
                "model": "The Reeder–Jol wall is Ilan–Amit point 4, point 19, Humbert's gorge dam, or a separate feature",
                "predicts": "Survey coordinates place the boulder, pothole and wall so they can be registered to Ilan–Amit's numbered plan. The repository's visual crosswalk does not tie point 3 to this sequence.",
                "confirm_if": "Coordinates register the wall to one numbered point within its error.",
                "contradict_if": "Coordinates register the wall away from every numbered point (a separate feature).",
                "inconclusive_if": "Coordinates without a stated datum or control.",
                "silent_if": "No coordinates.",
                "label": "EVIDENCE for the alternatives.",
            },
            {
                "family": "GPR detection (wave1 T09 report)",
                "model": "Field-survey plan",
                "predicts": "GPR profiles give no target-depth detection at the intake (poor performance in saline marl).",
                "confirm_if": "Profiles report low penetration or no interpretable reflectors at the intake.",
                "contradict_if": "Profiles show interpretable reflectors at 1.3–1.6 m at the intake.",
                "inconclusive_if": "Profiles without depth calibration.",
                "silent_if": "No GPR data.",
                "label": "INFERENCE recorded in the T09 report.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit decision classes; XII 10; entry 25; IV/17; rarity; closed tests", "reason": "No registered class uses the aqueduct survey."},
        ],
    },
    {
        "id": "zertal-vol-1",
        "title": "Zertal 1992, Manasseh Hill Country Survey vol. I (14 Stage 2 rarity units)",
        "holder": "Library (not obtained; Berkeley library day planned)",
        "requested": "Not requested",
        "request_source": "research/rarity/kohlit/stage2/addendum_s2/ADDENDUM.md ('Not read'); shared status file 'Next'",
        "request_detail": "Units S103, S153, S178, S563, S778, S806 (main set) and S112, S137, S144, S152, S157, S203, S780, S798 (pre-70 set only).",
        "status": "not_obtained",
        "status_note": "Not in the Drive index (Zertal folder holds vols 2–4 only).",
        "arrived_before_registration": [],
        "exposure": [],
        "questions": ["R07"],
        "active_questions": [],
        "entries": ["11", "60"],
        "reserved": False,
        "handling": "Code under the frozen Stage 2 protocol and match.py (b7a682b), following addendum_s2/PROCEDURE.md; two coders as before.",
        "decision_task": None,
        "decision_none_reason": "No decision class uses these units.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [],
        "rarity": {"units_main": ["S103", "S153", "S178", "S563", "S778", "S806"], "units_pre70_only": ["S112", "S137", "S144", "S152", "S157", "S203", "S780", "S798"]},
        "other_predictions": [
            {
                "family": "Rarity count, registered rules (preregistration §6; RESULTS headline after both addenda)",
                "model": "Headline branch A, survey level: k = 0, f = 20, m = 313 of 333",
                "predicts": "The verdict 'not measurable from available evidence' cannot change: Vol. I touches 6 main-set units, so k ≤ 6 while m ≥ 307.",
                "confirm_if": "After coding, m ≫ k still holds (deterministic bound).",
                "contradict_if": "Impossible under the bound.",
                "inconclusive_if": "Not applicable.",
                "silent_if": "Not applicable.",
                "label": "INFERENCE: arithmetic bound on registered numbers.",
            },
            {
                "family": "Observation-process audit (rarity/kohlit/observation_process/README.md)",
                "model": "Absence statements are site-scoped",
                "predicts": "Every new C2 FAIL rests on a site-level absence statement ('Cisterns: none' or similar) that gives no search radius over the 1 km northern sector. Under the audit's scope rule f stays 0.",
                "confirm_if": "Each new FAIL cites a site-record absence without a radius.",
                "contradict_if": "A new FAIL rests on a statement that a defined area of the northern sector was searched.",
                "inconclusive_if": "No new FAIL.",
                "silent_if": "Volume not obtained.",
                "label": "EVIDENCE: 61 of the 63 absence statements in the rarity count are Zertal's 'Cisterns: none'; none gives a search radius.",
            },
            {
                "family": "Reference rate (not a model test)",
                "model": "Vols 2–4 outcome",
                "predicts": "INFERENCE: if vol. I resembles vols 2–4 (19 of 60 main-set Zertal units became C2 FAIL), about 2 of the 6 main-set units become C2 FAIL. Recorded as a calibration check, not scored as a model test.",
                "confirm_if": "1–3 main-set C2 FAILs.",
                "contradict_if": "0 or more than 3 (no model is affected).",
                "inconclusive_if": "Not applicable.",
                "silent_if": "Volume not obtained.",
                "label": "INFERENCE.",
            },
        ],
        "no_prediction": [
            {"family": "Koḥlit chain models", "reason": "None of the 14 units is one of the 28 chain models."},
            {"family": "Koḥlit decision classes; XII 10; entry 25; IV/17; closed tests", "reason": "Unrelated."},
        ],
    },
    {
        "id": "kochavi-1972",
        "title": "Kochavi (ed.) 1972, Judaea, Samaria and the Golan: survey chapters by Kallai (Benjamin), Gophna and Porat (Ephraim and Manasseh), Bar-Adon (Judean Desert and Jordan plain)",
        "holder": "Library (not obtained; no online scan found)",
        "requested": "Not requested",
        "request_source": "research/feature_workbench/decisions/plans.json (decisions-kallai-pool: not_requested); shared status file 'Next'",
        "request_detail": "Key pages: Kallai pp. 172–173 (sites 65–66, ʿEin Samiya); the chapters' entries for the chain models and rarity units.",
        "status": "not_obtained",
        "status_note": "Not in the Drive index.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Highlands of Many Cultures (which summarises Kallai for Kh. el-Marjama, p. 732) and HA 76 p. 19 are already inspected; statements repeated from Kallai there are exposed.",
        ],
        "questions": ["R07", "R09"],
        "active_questions": [3],
        "entries": ["11", "60"],
        "reserved": False,
        "handling": "Ordinary library intake. Read Kallai pp. 172–173 first, after this register is pushed. Rarity units are coded under the frozen Stage 2 protocol.",
        "decision_task": "decisions-kallai-pool",
        "decision_coverage": 1.0,
        "decision_coverage_reason": "Kallai pp. 172–173 are the named record of the pool.",
        "chain_record_ids": ["REC-KALLAI-1972", "REC-BAR-ADON-1972", "REC-GOPHNA-PORAT-1972"],
        "chain_coverage": {"default": 0.5},
        "registry": [
            {"record": "P60-T3", "prediction": "Next desk test is Kallai pp. 172–173 with a dated pool plan. Follows the Kallai decision rows: a pool not east, or dated outside both windows, excludes the samiya-kallai and yanun-marjama classes (c06, c07, c09, c10)."},
            {"record": "P60-T9", "prediction": "Locates Bar-Adon 1972 site 83 (map reference) only; no scoring before that. No prediction on features."},
            {"record": "P60-T2", "prediction": "INFERENCE: Bar-Adon's survey chapter may list ʿEin el-Ghuweir. P60-T2 predicts shafts or pits among or by the graves north of the building. Its named desk test is Bar-Adon's ʿEin el-Ghuweir report, which is a separate publication; the survey entry alone is expected to be inconclusive."},
        ],
        "closed_results": [],
        "rarity": {"units_touched_stage2": 75, "units_touched_main": 66},
        "other_predictions": [
            {
                "family": "Rarity count (registered rules)",
                "model": "Each chain model with two of three conditions",
                "predicts": "Each predicts that its missing third condition is recorded. If any is confirmed at survey level, k rises from 0 for that unit. The two-of-three units these chapters cover are S1667, S2376 (Kallai), S845, S1137 (Gophna and Porat), S6040, S1283, S2430, S3961 (Bar-Adon).",
                "confirm_if": "The unit's missing condition is coded MATCH by match.py.",
                "contradict_if": "Coded FAIL (needs an explicit absence statement; silence is never a FAIL).",
                "inconclusive_if": "Coded UNKNOWN.",
                "silent_if": "The entry is missing from the chapter.",
                "label": "EVIDENCE: unit values in addendum_s2/results/unit_results.csv.",
            },
            {
                "family": "Rarity verdict",
                "model": "Headline branch A, survey level",
                "predicts": "No prediction on the verdict: these chapters touch 66 main-set units, and the preregistration fixes no number for 'm ≫ k'. The register records k, f and m after coding.",
                "confirm_if": "Not applicable.",
                "contradict_if": "Not applicable.",
                "inconclusive_if": "Not applicable.",
                "silent_if": "Not applicable.",
                "label": "INFERENCE.",
            },
        ],
        "no_prediction": [
            {"family": "XII 10 strings; entry 25; IV/17; closed tests", "reason": "Unrelated."},
        ],
    },
    {
        "id": "l656-field-file",
        "title": "Michael Dadon's IV/17 excavation file, permit L-656: plan with the north mouth, threshold section and levels, level and basket registers (656.17, 656.20), locus list, method notes",
        "holder": "Archive of the Archaeology Staff Officer for Judea and Samaria (named in Sion 2002 p. 82); present holding unverified",
        "requested": "Not requested (the 7 Oct IAA request is related only)",
        "request_source": "research/feature_workbench/coverage/README.md; decisions plans.json (decisions-iv17-l656)",
        "request_detail": "See coverage/volume_inputs.json field records.",
        "status": "not_obtained",
        "status_note": "No specific request sent.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Sion 2002 pp. 61–64 and Plan 5 are inspected; survey coins 60/61 and basket numbers are published without contacts.",
        ],
        "questions": ["R02", "R08", "R09"],
        "active_questions": [],
        "entries": ["25"],
        "reserved": False,
        "handling": "Ordinary intake. Before reading threshold levels or wall contacts, freeze the Entry 25 branches and an aspect rule (decisions README).",
        "decision_task": "decisions-iv17-l656",
        "decision_coverage": 1.0,
        "decision_coverage_reason": "The file is the named record. Rows needing a mouth bearing are replaced by 'bearing undetermined' rows (RANKING_PLAN).",
        "decision_row_filter": "bearing_undetermined",
        "chain_record_ids": [],
        "registry": [],
        "coverage_cases": [
            {"case": "coverage-volume-iv17", "prediction": "With the file alone, all 8 joins stay undeterminable. The file can supply cut outlines, levels, datum and the threshold surface, but every branch also needs a model declaration no record can supply: the target-zone outline (vertical branches) or origin point, sector and depth band (horizontal branches), plus a radial tolerance for single-cubit branches. Proposal: declare these before the file arrives."},
        ],
        "closed_results": [],
        "other_predictions": [],
        "no_prediction": [
            {"family": "Koḥlit; XII 10; rarity; closed tests", "reason": "Unrelated."},
        ],
    },
    {
        "id": "kenyon-iii-plates",
        "title": "Kenyon and Holland 1981, Excavations at Jericho III, plate volume: Trench II eastern section (local 37.50–38.00 m N / 8.17 m H) and Pl. 111b",
        "holder": "Library (not obtained)",
        "requested": "Not requested",
        "request_source": "decisions plans.json (decisions-kenyon-section); added by this register because the decisions module ranks it second",
        "request_detail": "Not on the brief's list. Added so the ranking includes the record the decisions module needs for the quarry-pit classes.",
        "status": "not_obtained",
        "status_note": "Drive holds the text volume only.",
        "arrived_before_registration": [],
        "exposure": [
            "EVIDENCE: Kenyon III text pp. 119–121, 173–174 is inspected (about 18 graves; later undated quarry pits cutting them).",
        ],
        "questions": ["R07", "R09"],
        "active_questions": [2],
        "entries": ["60"],
        "reserved": False,
        "handling": "Ordinary library intake.",
        "decision_task": "decisions-kenyon-section",
        "decision_coverage": 1.0,
        "decision_coverage_reason": "The section and plate are the named record.",
        "chain_record_ids": ["REC-KENYON-III-PLATES"],
        "chain_coverage": {"default": 1.0},
        "registry": [
            {"record": "P60-T1", "prediction": "Its next desk test names this section and Pl. 111b. Follows the Kenyon decision rows."},
        ],
        "coverage_cases": [
            {"case": "coverage-volume-tell-es-sultan", "prediction": "Trench II joins stay undeterminable: the plates give local levels, but the target still lacks a declared distance band and origin."},
        ],
        "closed_results": [],
        "other_predictions": [],
        "no_prediction": [
            {"family": "XII 10; entry 25; IV/17; rarity; closed tests", "reason": "Unrelated."},
        ],
    },
    {
        "id": "facsimile-editions-3d-scan",
        "title": "3D scan of the EDF plates at XII 10",
        "holder": "Facsimile Editions, London",
        "requested": "8 Oct 2026 about 04:09 UTC",
        "request_source": "research/ACTIVE_TEST.md",
        "request_detail": "",
        "status": "declined",
        "status_note": "Declined 8 Oct 2026. No item will arrive. Listed for completeness; not ranked.",
        "arrived_before_registration": [],
        "exposure": [],
        "questions": ["R07"],
        "active_questions": [1],
        "entries": ["60"],
        "reserved": True,
        "handling": XII10_HANDLING,
        "decision_task": None,
        "decision_none_reason": "Declined.",
        "chain_record_ids": [],
        "registry": [],
        "closed_results": [],
        "other_predictions": [],
        "no_prediction": [{"family": "All", "reason": "Declined; nothing will arrive."}],
        "unranked": True,
    },
]
