export type DossierSource = { id: string; title: string; locator: string; url: string; note: string; kind?: "plan" | "text" | "photograph" | "reconstruction" };
export type DossierFeature = { name: string; kind: "Reported remains" | "Published reconstruction" | "Project inference"; observation: string; limit: string; sourceIds: string[] };
export type DossierPhase = { label: string; detail: string; sourceIds: string[] };
export type PlaceDossier = { id: string; name: string; subtitle: string; summary: string; entryIds: string[]; comparisonIds?: string[]; phases: DossierPhase[]; features: DossierFeature[]; sourceIds: string[]; unresolved: string };
export type ArgumentBranch = { id: string; label: string; attribution: string; reading: string; requirements: string[]; chronology: string; evidence: string; open: string; sourceIds: string[] };
export type EntryArgument = { entryId: string; summary: string; branches: ArgumentBranch[] };
const repo = "https://github.com/quadrin/CopperScroll/blob/main/";
const record = (path: string) => `${repo}${path}`;

export const dossierSources: DossierSource[] = [
  { id: "qumran-plan", title: "Ilan & Amit · Qumran aqueduct", locator: "1989 pp. 283–288 · Fig. 1 p. 283", url: record("research/sites/ilan_amit_1989_plan_review.md"), kind: "plan", note: "Numbered route plan with sections, scales and north arrows. Point 4 is a proposed lost dam. Original image has no verified open licence; the linked review records the distinction between remains and reconstruction." },
  { id: "qumran-reconstruction", title: "Ritmeyer · Qumran settlement reconstruction", locator: "Ilan & Amit 1989 · Fig. 7 p. 287", url: record("research/assets/plans/ilan-amit1989/README.md"), kind: "reconstruction", note: "Published reconstruction credited to L. Ritmeyer. It supplies no independent excavated wall geometry or construction date; linked archival record, rather than an unlicensed image reproduction." },
  { id: "qumran-tunnel", title: "Magen & Peleg · Qumran tunnel", locator: "2018 pp. 76–79 · Figs. 86–87", url: record("research/sites/qumran_photo_correspondence.md"), kind: "photograph", note: "Photographic correspondence with Reeder’s Fig. 2 is reviewed in the source record; the caption-direction conflict and missing survey registration are retained." },
  { id: "qumran-comparison", title: "Qumran feature comparison", locator: "Entries 21–22 · separate source-plan frames", url: `${import.meta.env?.BASE_URL ?? "/"}research/entry21-comparison.html`, kind: "plan", note: "Project comparison with four low-confidence candidates. Its highlights are selection aids in source-plan coordinates, not mapped footprints or uncertainty radii." },
  { id: "entry25-edition", title: "Puech · Cave of the Column", locator: "2015 pp. 59–60 · VI 1–6", url: record("research/measurements/cycle4/puech_entry25.md"), kind: "text", note: "Existing original-page audit. Pillar and terrace alternatives are kept separate, as are cave-level and individual-mouth aspect. No new reading of the metal is claimed." },
  { id: "iv17-plan", title: "Sion · IV/17 cave", locator: "ʿAtiqot 41 (2002) pp. 61–64 · Plan 5 p. 63", url: "https://publications.iaa.org.il/atiqot/vol41/iss1/6/", kind: "plan", note: "Survey plan and excavation description: two openings and a rock-cut dividing pillar. Plan geometry does not establish the date of the threshold or blocking wall; the L-656 field file remains a dependency." },
  { id: "entry25-test", title: "IV/17 conditional feature assessment", locator: "Northern aperture · assessment reviewed 2 October 2026", url: record("research/assessments/entry25_iv17/README.md"), kind: "text", note: "Form compatibility is distinguished from identification and a digging location. IV/11 and Twin Cave receive the same retained reading and aspect comparisons." },
  { id: "doq-plan", title: "Amit · Water system of Doq", locator: "1989 pp. 223–224 · Fig. 1 photograph p. 223; Fig. 2 plan p. 224", url: record("research/measurements/cycle3/doq_anchor.md"), kind: "plan", note: "The inspected plan identifies the water system. It does not identify or date a drying room, guard post or its eastern corner. Later pages 225–228 were outside this recorded inspection." },
  { id: "doq-reading", title: "Doq · edition alternatives", locator: "Puech 2006 p. 192 / 2015 p. 67; Milik 1962 D19 p. 292; Lefkovits 2000 pp. 232–235", url: record("research/sites/dok_achor_feature_tests.md"), kind: "text", note: "Drying place and guard post require different installations. In the guard-post branch, eastern can qualify the corner or the building; archaeology cannot select the disputed word." },
  { id: "photo-audit", title: "Original-photo registration audit", locator: "VII 11, IX 7, X 15–16 · 6 October 2026", url: record("research/text/plate_check.md"), kind: "text", note: "Earlier printed-plate leanings are recorded separately. The target words on the available original photographs were not authenticated with neighbouring Hebrew and cut placement, so they do not adjudicate the readings." },
  { id: "siloam-plan", title: "Greenhut & Mazor · Dam and receiving basin", locator: "ʿAtiqot 101 (2020) Plan 1 p. 74*; Fig. 5 p. 76*; conclusion p. 83*", url: "https://publications.iaa.org.il/atiqot/vol101/iss1/6/", kind: "plan", note: "L103 crosses W1 into the small L102/L104 receiving basin. The reported 0.75 m height is above this basin’s floor, not a surveyed datum inside the larger basin." },
  { id: "siloam-names", title: "Szanton · The pools’ ancient names", locator: "ʿAtiqot 113 (printed 2023) pp. 34–42 · Figs. 1, 4, 6", url: "https://publications.iaa.org.il/atiqot/vol113/iss1/3/", kind: "text", note: "The publication distinguishes the Silwan tunnel-mouth pool and larger Birket al-Hamra and proposes different ancient names. These associations are hypotheses, rather than independent readings of the scroll." },
  { id: "siloam-2024", title: "Szanton, Vukosavović & Berko · Birket al-Hamra", locator: "2024 pp. 27*, 33*–39* · Fig. 5 excavation plan; Fig. 6 reconstruction", url: "https://cityofdavid.org.il/wp-content/uploads/2025/12/New-archaeological-discoveries-in-the-excavations-of-Birket-al-Hamra-in-Jerusalem.pdf", kind: "plan", note: "Fig. 5 maps exposures; Fig. 6 reconstructs a complete stepped basin. Water and excavation depth left the dam/wall stratigraphic relationship unresolved (p. 33* n. 3)." },
  { id: "siloam-test", title: "Entry 49 · Basin, function and under-pipe relation", locator: "Milik 1960 pp. 142, 152; Puech 2015 pp. 85–86, 91–93; main-pool test 6 October 2026", url: record("research/measurements/cycle15/siloam_bathing.md"), kind: "text", note: "The reviewed main-basin claim ended as not identifiable. A receiver-side datum cannot be moved into Birket; the bath function and a dated main-basin junction remain unresolved." },
  { id: "siloam-readings", title: "Entry 49 · Reading register", locator: "X 15–16 · Lefkovits 2000 pp. 352–354; Puech 2006 p. 200 / 2015 p. 92", url: record("text/readings.json"), kind: "text", note: "The current base text’s baths / Raḥil(?) differs from Puech’s outlet / restored Siloam branch and Lefkovits’s water-closet / Jehu branch. No single geographical requirement can be borrowed across them." },
  { id: "jericho-spring", title: "Dorrell · The Spring at Jericho", locator: "PEQ 125 (1993) pp. 95–97, 110–112 · Figs. 1–4 pp. 98–99; 20–21 p. 107", url: record("research/agent_review_2026-10-07/followup/A_jericho_spring_reservoir.md"), kind: "photograph", note: "Historical photographs document an irregular spring basin and a distinct reservoir built in 1898. They do not date the earlier basin’s construction to the scroll’s period." },
  { id: "jericho-graves", title: "Kenyon · Jericho graves and cisterns", locator: "Jericho II (1965) pp. 169, 276–277, 539–544 · Figs. 91, 137.2", url: record("research/agent_review_2026-10-07/followup/C_kenyon_jericho_II_and_kh_yanun.md"), kind: "plan", note: "D9, NS1 and graves are separately reported features. NS1 has no surveyed mouth plan; their presence in a northern sector establishes no dated tomb-at-pit-mouth relation." },
  { id: "jericho-succession", title: "Kenyon · North-slope succession", locator: "Jericho III Text (1981) pp. 173–174 · Trench II / Site O, stages XXIV–XXV", url: record("research/agent_review_2026-10-07/followup/C_kenyon_jericho_II_and_kh_yanun.md"), kind: "text", note: "First-century graves precede later undated quarry pits cutting them. This succession does not establish contemporaneous accessible mouths. Separate Plate 111b and the named section remain unread in this review." },
  { id: "kohlit-readings", title: "Koḥlit · Relationship reading registry", locator: "II 13–15; XII 10–13 · Puech 2015 pp. 13–14 n. 49; Lefkovits 2000 pp. 425–426", url: record("research/agent_review_2026-10-07/wave2/W2B_model_v1/registry_v2_entry60.json"), kind: "text", note: "Koḥlit remains unlocated. The registry retains north-facing, concealed, buried and Janoaḥ branches and separate exploratory use windows. It records inherited edition readings, not a new reading of XII 10." },
  { id: "marjama-plan", title: "Mazar · Khirbet Marjameh", locator: "IEJ 45 (1995) pp. 85–87, 95, 97 · Figs. 1 p. 86, 7 p. 91, 16 p. 99", url: record("research/agent_review_2026-10-07/followup/B_kh_el_marjama.md"), kind: "plan", note: "Fig. 7 is the summit excavation plan, with north pointing page-left. Cistern L20 was unexcavated and undated. The spring lies below the southern cliff; the eastern fertile valley is not an observed ancient channel." },
  { id: "samiya-basin", title: "Zohar · Tell Marjame / ʿEin Samiya", locator: "IEJ 30 (1980) pp. 219–220; HA 76 (1981) p. 19", url: record("research/agent_review_2026-10-07/followup/B_kh_el_marjama.md"), kind: "text", note: "The IEJ notice records a basin beneath a Byzantine church crypt at the spring and the church’s destruction during pumping-station expansion. The HA report is the same 1979–1980 field campaign and supplies no pool or Roman water-installation phase." },
  { id: "samiya-survey", title: "Highlands of Many Cultures · Samiya region", locator: "1997 pp. 732–735, 741", url: record("research/agent_review_2026-10-07/followup/B_kh_el_marjama.md"), kind: "text", note: "North/NNE shaft-tomb fields are Bronze Age. Roman–Byzantine burial caves with ossuary fragments are reported S/SE, not at a documented northern pit mouth. Surface period notices do not date an individual feature." },
  { id: "kallai-pool", title: "Kallai · Unlocated rock-cut pool dependency", locator: "Kochavi (ed.), Archaeological Survey 1967–1968 (1972) pp. 172–173 · sites 65–66", url: "https://www.nli.org.il/he/books/NNL_ALEPH990019622650205171/NLI", kind: "plan", note: "Needed pages and associated plans remain uninspected in the recorded review. The Kallai pool cannot be assigned to the church-crypt basin or dated from neighbouring occupation." },
  { id: "jericho-netzer", title: "Netzer · Royal pools and hydraulic states", locator: "1983 pp. 100–101, 104–106; 2001 pp. 74, 84–87, 100, 131–133", url: record("research/assessments/entry29_jericho_pools/kotar-netzer1983.md"), kind: "plan", note: "Early pools are approximately 18 × 13 m; the later joined A(B)101 is approximately 32 × 18 m. A(B)171 is a reported drainage segment. These phases and axes require separate tests." },
  { id: "jericho-trumper", title: "Trümper · Hasmonean swimming pools", locator: "2018 pp. 280–286 · Figs. 18–22; image credits p. 296", url: "https://edition-topoi.org/download_pdf/bsa_053_10.pdf", kind: "plan", note: "CC BY-NC 3.0 publication, retaining original Netzer image credits. Its selected swimming-pool catalogue is not a complete inventory of ancient reservoirs or a new independent excavation." },
  { id: "jericho-pipe", title: "A(C)94 · Northern-wall pipe test", locator: "Netzer 2001 pp. 52, 57–59 · Plan 13; Trümper 2018 pp. 283–284", url: record("research/assessments/entry29_jericho_pools/ac94_pipe_test.md"), kind: "plan", note: "A found northern-wall pipe can be compared independently of a later open-channel fragment. The needed named wall face, contemporaneous floor and phased terminal contact remain unresolved." },
  { id: "jericho-entry29", title: "Entry 29 · Retained hydraulic readings", locator: "Puech 2015 pp. 62–65; Milik 1960 p. 140, pp. 148–149 · VII 3–7", url: record("research/measurements/cycle15/jericho_conduit.md"), kind: "text", note: "Jericho and the collection-installation continuation are restored. 24/27 cubits, partial conduit, collector and damaged-name models remain separate; an unnamed drain cannot confirm the damaged name." },
  { id: "jericho-inventory", title: "Jericho water installations · Regional inventory", locator: "Reviewed 6 October 2026 · source-specific pages and contact gaps", url: record("research/assessments/entry29_jericho_pools/regional_inventory_2026-10-06.md"), kind: "text", note: "Selected reports include excavated, destroyed, historical and unresolved water features. Coverage and the regional denominator remain unknown; repeated publication of one campaign is not independent corroboration." },
];

export const placeDossiers: PlaceDossier[] = [
  { id: "kh_qumran", name: "Khirbet Qumran", subtitle: "Aqueduct, cisterns and cliff caves", summary: "A well-documented water system offers several distinct structures to compare with the scroll. The source plans separate surviving channels, proposed lost structures and settlement reconstructions.", entryIds: ["20", "21", "22", "23", "24", "25"], phases: [
    { label: "Published water-system sequence", detail: "The aqueduct plan distinguishes observed route elements from a proposed earlier dam at point 4. Its settlement reconstruction does not independently date that lost structure.", sourceIds: ["qumran-plan", "qumran-reconstruction"] },
    { label: "Feature chronology remains separate", detail: "A tunnel photograph, pottery nearby and the settlement’s occupation history cannot establish the date of every inlet, fissure or basin named in an entry.", sourceIds: ["qumran-tunnel", "qumran-comparison"] },
  ], features: [
    { name: "Numbered aqueduct route", kind: "Reported remains", observation: "Ilan–Amit Fig. 1 records a channel route, tunnel inset, sections and named points for comparison.", limit: "Source-plan frames are not a surveyed geographic registration of the scroll’s individual landmarks.", sourceIds: ["qumran-plan"] },
    { name: "Lost dam at point 4", kind: "Published reconstruction", observation: "The authors propose a former dam as part of their hydraulic sequence.", limit: "Its drawn location is a reconstruction; it cannot stand in for an observed wall face or phase-controlled contact.", sourceIds: ["qumran-plan"] },
    { name: "Tunnel and two fissures", kind: "Reported remains", observation: "Magen–Peleg describe and photograph the tunnel; project comparison recognises a correspondence with Reeder’s image.", limit: "Caption direction conflicts and missing survey stations prevent a precise intake or hiding-place position.", sourceIds: ["qumran-tunnel", "qumran-comparison"] },
    { name: "Cave IV/17 comparison", kind: "Project inference", observation: "A two-opening cave with a dividing pillar is an explicit feature comparison for entry 25.", limit: "Its form is not unique, and its mouth bearings, ancient thresholds and architectural dates are unresolved.", sourceIds: ["iv17-plan", "entry25-test"] },
  ], sourceIds: ["qumran-plan", "qumran-reconstruction", "qumran-tunnel", "qumran-comparison", "iv17-plan", "entry25-test"], unresolved: "No individually surveyed deposit position follows from these source-plan and photograph correspondences." },
  { id: "doq", name: "Doq / Jebel Qarantal", subtitle: "A named fortress and a disputed installation", summary: "The Doq association and the disputed building word answer different questions. A summit fortress and its water system provide a setting; they do not select drying place or guard post.", entryIds: ["31", "32"], phases: [
    { label: "Hasmonean fortress context", detail: "Ancient literary references place Dok/Dagon in the Jericho region. The modern summit association is a topographic proposal with its own evidence chain.", sourceIds: ["doq-plan"] },
    { label: "Required installation undated", detail: "The inspected water-system plan identifies neither a securely dated guard post nor a drying place. A non-rebuilding argument cannot date their construction or accessible use.", sourceIds: ["doq-plan", "doq-reading"] },
  ], features: [
    { name: "Fortress water system", kind: "Reported remains", observation: "Amit’s Fig. 2 is the water-system plan; Fig. 1 is a photograph. These establish the source’s depicted installation types.", limit: "An aqueduct or cistern near a fortress is not the eastern corner required by entry 31.", sourceIds: ["doq-plan"] },
    { name: "Drying place", kind: "Project inference", observation: "Puech’s reading requires a drying place with an eastern corner.", limit: "No matching installation has been established in the checked records. Incomplete coverage cannot demonstrate absence.", sourceIds: ["doq-reading", "photo-audit"] },
    { name: "Guard-post corner", kind: "Project inference", observation: "Milik/Lefkovits retain a guard post; eastern may qualify the corner or the guard post itself.", limit: "The summit’s eastern edge is not an observed ancient building corner.", sourceIds: ["doq-reading"] },
  ], sourceIds: ["doq-plan", "doq-reading", "photo-audit"], unresolved: "The locality proposal is stronger than the identification of a particular installation, ancient surface or digging point." },
  { id: "jer_siloam", name: "Siloam / Silwan", subtitle: "Keep each basin and water contact distinct", summary: "Several pools, receivers, channels and naming hypotheses occupy this area. A photographed stepped basin, a tunnel-mouth pool and a small receiving basin must retain their separate physical identities.", entryIds: ["49"], phases: [
    { label: "Early Roman pool proposals", detail: "Published reports propose Early Roman construction and use for particular exposed structures. Basin-wide reconstructions and ancient-name associations remain interpretive.", sourceIds: ["siloam-names", "siloam-2024"] },
    { label: "Small receiver’s floor and later channel", detail: "The receiving floor’s coin/contact chain and L103’s proposed later insertion concern those features. They do not transfer a construction date to the whole large basin or a different pipe.", sourceIds: ["siloam-plan", "siloam-test"] },
  ], features: [
    { name: "Birket al-Hamra, larger stepped basin", kind: "Reported remains", observation: "The 2024 excavation plan records separate exposures of monumental steps and pool remains.", limit: "No named, surveyed under-pipe point inside this basin is established in the inspected plans; bath function and ancient naming remain disputed.", sourceIds: ["siloam-2024", "siloam-test"] },
    { name: "Silwan tunnel-mouth pool", kind: "Published reconstruction", observation: "Szanton proposes this smaller installation as Early Roman Siloam, distinguishing it from Birket.", limit: "A compatible name and hydraulic setting establish no trough or under-feature relation for the scroll.", sourceIds: ["siloam-names", "siloam-test"] },
    { name: "L103 and receiver L102/L104", kind: "Reported remains", observation: "The channel crosses W1 and enters the small southeastern receiver. Its reported height is 0.75 m above that receiver’s floor.", limit: "Channel-bottom height is not a structural underside, ancient ground datum or point belonging to the larger basin.", sourceIds: ["siloam-plan", "siloam-test"] },
    { name: "Complete stepped-pool outline", kind: "Published reconstruction", observation: "The 2024 Fig. 6 supplies a full-basin reconstruction, separate from Fig. 5’s excavation exposures.", limit: "The reconstruction cannot fill an unobserved junction or unresolved phase contact.", sourceIds: ["siloam-2024"] },
  ], sourceIds: ["siloam-plan", "siloam-names", "siloam-2024", "siloam-test", "siloam-readings", "photo-audit"], unresolved: "The reviewed main-basin model is not identifiable from available evidence. The open dependency is a dated basin–conduit junction and floor, with evidence for the required function." },
  { id: "tell_es_sultan", name: "Tell es-Sultan / ʿAin es-Sultan", subtitle: "Pool east, pit north: test the relations separately", summary: "The Tell es-Sultan proposal for Koḥlit connects an eastern spring basin with northern pits and graves. Each feature must be located and dated independently before their relationship can identify an entry.", entryIds: ["11", "29", "60"], comparisonIds: ["samiya_marjama"], phases: [
    { label: "First-century graves; later quarry pits", detail: "Kenyon describes first-century north-slope graves followed by quarry pits cutting them. The pits are later and undated; succession does not establish jointly accessible mouths.", sourceIds: ["jericho-succession"] },
    { label: "Nineteenth-century spring basin", detail: "Historical images document an irregular basin at the spring. Its earlier construction and northern-corner datum are unknown.", sourceIds: ["jericho-spring"] },
    { label: "1898 reservoir", detail: "A separately documented modern reservoir is too late for either saved exploratory scroll-use window. That exclusion concerns this reservoir, not every spring installation.", sourceIds: ["jericho-spring", "kohlit-readings"] },
  ], features: [
    { name: "Historical basin at the eastern foot", kind: "Reported remains", observation: "Dorrell’s photographs and accounts place the basin beside the spring east of the tell.", limit: "The qualitative relation is compatible; an ancient construction date and specified northern corner are unestablished.", sourceIds: ["jericho-spring"] },
    { name: "NS1 cistern and D9 shaft", kind: "Reported remains", observation: "Kenyon separately describes northern-sector features and associated finds.", limit: "Find dates do not date an accessible mouth. NS1 has no surveyed mouth plan and no observed tomb-at-mouth relation.", sourceIds: ["jericho-graves"] },
    { name: "North-slope graves and quarry pits", kind: "Reported remains", observation: "The report records pits cutting earlier graves.", limit: "That order cannot verify a contemporary pit-mouth and tomb-mouth configuration.", sourceIds: ["jericho-succession"] },
    { name: "Koḥlit = Tell es-Sultan", kind: "Project inference", observation: "Puech’s geographical proposal motivates testing the eastern-pool and northern-pit relations here.", limit: "Koḥlit is unlocated; regional names and entry order cannot select this anchor by themselves.", sourceIds: ["kohlit-readings"] },
  ], sourceIds: ["jericho-spring", "jericho-graves", "jericho-succession", "kohlit-readings"], unresolved: "No individual deposit is located. The north-of-tell test requires a dated pit-mouth / tomb-mouth relation; the eastern-pool test requires a construction date." },
  { id: "samiya_marjama", name: "Kh. el-Marjama / ʿEin Samiya", subtitle: "Comparison dossier · no atlas coordinate assigned", summary: "This alternative Koḥlit comparison contains a spring, an undated summit cistern, a destroyed church-crypt basin and separate burial sectors. Their individual identities and dates cannot be combined into a single ancient layout.", entryIds: ["11", "60"], comparisonIds: ["tell_es_sultan"], phases: [
    { label: "Bronze and Iron Age excavated remains", detail: "Mazar and Zohar record dated excavated contexts. Surface Hellenistic/Roman notices on the tell do not date a water feature or distinguish Early from Late Roman use.", sourceIds: ["marjama-plan", "samiya-basin", "samiya-survey"] },
    { label: "Byzantine church-crypt basin", detail: "Zohar’s IEJ notice describes water collection beneath a Byzantine church crypt. The basin has no independent construction date in that notice.", sourceIds: ["samiya-basin"] },
    { label: "Modern pumping-station expansion", detail: "The church was destroyed when the pumping station was enlarged. Survival and documentation gaps must remain part of the comparison.", sourceIds: ["samiya-basin"] },
  ], features: [
    { name: "Crypt basin at the spring", kind: "Reported remains", observation: "An explicit basin is reported beneath the church crypt southwest of the tell.", limit: "It conflicts with the selected east-of-tell relation; its notice does not locate Kallai’s separate rock-cut pool.", sourceIds: ["samiya-basin", "marjama-plan"] },
    { name: "Summit cistern L20", kind: "Reported remains", observation: "The summit plan marks a bell-shaped cistern south of Building 10, near the southern cliff edge.", limit: "It was unexcavated and undated. It is not an observed pit north of the tell with graves at its mouth.", sourceIds: ["marjama-plan"] },
    { name: "Northern shaft-tomb sector", kind: "Reported remains", observation: "The north/NNE shaft-tomb fields are recorded as Intermediate and Middle Bronze Age.", limit: "Their regional position establishes no dated pit-mouth relation. Roman–Byzantine ossuary burial caves are in a different S/SE sector.", sourceIds: ["samiya-survey"] },
    { name: "Kallai rock-cut pool", kind: "Project inference", observation: "The relationship workbench retains this source-dependent comparison with no invented feature position.", limit: "The exact original pp. 172–173, site context and plan remain needed to locate and date it.", sourceIds: ["kallai-pool"] },
  ], sourceIds: ["marjama-plan", "samiya-basin", "samiya-survey", "kallai-pool"], unresolved: "The unlocated Kallai pool remains unknown. Excluding the southwest crypt basin from an east-of-tell model does not exclude the entire Marjama/Samiya region." },
  { id: "jericho_palaces", name: "Jericho royal palaces", subtitle: "A succession of pool and conduit arrangements", summary: "The early pool pair, joined Herodian basin and separate Area AC installations belong to different physical and chronological models. Compare the required wall–water relation within one named state.", entryIds: ["29"], phases: [
    { label: "Early paired pools", detail: "Netzer reports two pools of approximately 18 × 13 m. Their original inlet positions and the selected ancient wall faces remain unresolved.", sourceIds: ["jericho-netzer", "jericho-trumper"] },
    { label: "Herodian joined basin A(B)101", detail: "The joined installation is approximately 32 × 18 m, changing the longer-side axis. The reported A(B)171 drain does not establish its pool-wall aperture or a connected collector.", sourceIds: ["jericho-netzer", "jericho-entry29"] },
    { label: "Separate Area AC arrangements", detail: "A(C)94 has a found northern-wall pipe and a separate later open-channel fragment with an unresolved terminal connection. These cannot borrow a phase or datum from the early pool pair.", sourceIds: ["jericho-pipe"] },
  ], features: [
    { name: "Early northern and southern pools", kind: "Reported remains", observation: "Published plans distinguish the two basins and their later joining.", limit: "Exploratory offset bands overlap under retained numeral and measurement choices; no ancient channel-wall datum or deposit point is established.", sourceIds: ["jericho-netzer", "jericho-trumper"] },
    { name: "A(B)171 drainage segment", kind: "Reported remains", observation: "Netzer reports drainage toward eastern fields in the joined-basin context.", limit: "An outlet feeding a collector is a project interpretation. The collector and contemporaneous terminal contacts are not demonstrated.", sourceIds: ["jericho-entry29"] },
    { name: "A(C)94 northern-wall pipe", kind: "Reported remains", observation: "The publication records a pipe found in the northern wall and followed northwest.", limit: "A phase-controlled section tying its aperture, named wall face and contemporary floor is still needed.", sourceIds: ["jericho-pipe"] },
  ], sourceIds: ["jericho-netzer", "jericho-trumper", "jericho-pipe", "jericho-entry29", "jericho-inventory"], unresolved: "Entry 29 remains not identifiable from available evidence. Jericho itself is restored in one reading; the regional water-feature inventory has unresolved coverage." },
];

export const entryArguments: EntryArgument[] = [
  { entryId: "11", summary: "The east-of-Koḥlit pool relation is useful only after choosing and testing an explicit Koḥlit anchor. Neither the ancient pool nor its northern corner is identified.", branches: [
    { id: "kohlit-unplaced", label: "Koḥlit unplaced", attribution: "Preserved geographical relation", reading: "A pool east of Koḥlit and a northern-corner instruction.", requirements: ["An independently justified Koḥlit locality", "A pool east of that locality", "A dated northern corner and ancient surface"], chronology: "The pool must exist and be accessible in the relevant use phase; an adjacent ancient wall supplies no construction date.", evidence: "The name Koḥlit lacks a decisive outside location witness in the reviewed records.", open: "A locality witness or dated pool relation that discriminates between retained geographical proposals.", sourceIds: ["kohlit-readings"] },
    { id: "kohlit-sultan", label: "Tell es-Sultan proposal", attribution: "Puech 2015 pp. 13–14 n. 49", reading: "Apply the preserved east-of relation to the proposed Tell es-Sultan anchor.", requirements: ["Historical spring basin east of the tell", "Independent ancient construction/use phase", "The specified northern corner"], chronology: "The historical basin’s ancient date is unknown. The distinct 1898 reservoir fails both saved ancient-use windows.", evidence: "Dorrell supports a qualitative eastern-foot relation. Historical photographs do not backdate the basin.", open: "Sealed construction evidence at the spring-house wall or another phase-controlled pool observation.", sourceIds: ["kohlit-readings", "jericho-spring"] },
    { id: "kohlit-marjama", label: "Marjama / Samiya comparison", attribution: "Retained exploratory geographical assignment", reading: "Apply the same east-of-pool relation to a Marjama anchor.", requirements: ["Locate Kallai’s rock-cut pool independently", "An east-of-tell relation", "A construction/use phase for that pool"], chronology: "The southwest church-crypt basin cannot supply an ancient date or position for the unlocated Kallai pool.", evidence: "The only explicitly documented crypt basin lies southwest. Kallai’s exact pool pages and context remain needed.", open: "Kallai 1972 pp. 172–173 with the relevant plan and sites 65–66 context.", sourceIds: ["marjama-plan", "samiya-basin", "kallai-pool"] },
  ] },
  { entryId: "25", summary: "A two-opening form is a comparison criterion, rather than an identification. Pillar, terrace, directional attachment, ancient state and digging origin remain separate choices.", branches: [
    { id: "pillar", label: "Pillar cave", attribution: "Puech 2015 pp. 59–60", reading: "A cave associated with a pillar, two openings, an eastward aspect and a northern-opening instruction.", requirements: ["Pillar and two exterior openings", "Distinguishable northern member", "The selected eastward attachment", "Ancient threshold/floor datum for three cubits"], chronology: "Reported mouths and pillars do not establish their ancient architectural state. IV/17’s wall/threshold contacts remain unresolved.", evidence: "IV/17 and Twin Cave both supply broad form parallels. IV/11 supplies an internal pillar without an established exterior pair.", open: "A dated architectural contact and northern threshold datum in the IV/17 field record, evaluated against the retained controls.", sourceIds: ["entry25-edition", "iv17-plan", "entry25-test"] },
    { id: "terrace", label: "Platform / terrace", attribution: "Allegro alternative discussed by Puech", reading: "Retain a platform/terrace landmark instead of assuming the pillar sense.", requirements: ["An independently documented terrace association", "The same two-opening and directional constraints", "Ancient origin and datum for the digging instruction"], chronology: "A present terrace or platform requires its own date and coexistence with the relevant entrance arrangement.", evidence: "The saved comparison keeps terrace associations unknown where the publications do not report them.", open: "A source-supported terrace feature; pillar resemblance alone cannot satisfy this branch.", sourceIds: ["entry25-edition", "entry25-test"] },
  ] },
  { entryId: "29", summary: "The damaged name, restored Jericho, numeral and conduit relationship create different models. The site proposal cannot silently supply a missing reading or wall datum.", branches: [
    { id: "partial-conduit", label: "Partial conduit relation", attribution: "Defended damaged wording", reading: "A conduit related to a northern reservoir, with the damaged Qe-form left unresolved.", requirements: ["A named reservoir and a contemporaneous conduit contact", "The retained 24/27-cubit reading", "A source-supported origin, wall face and distance convention"], chronology: "Early pair and joined Herodian basin are separate states, with different longer-side axes.", evidence: "The observed A(B)171 drainage survives the narrow direction test, without positively identifying the damaged word or locating a deposit.", open: "A phase-controlled aperture, named wall face, floor and physical terminal relation.", sourceIds: ["jericho-entry29", "jericho-netzer"] },
    { id: "collector-restoration", label: "Collected-waters restoration", attribution: "Puech 2015 pp. 62–65", reading: "Restore a collection installation and, conditionally, Jericho.", requirements: ["An identified collecting installation", "Its contemporaneous connection to the selected reservoir", "The reading-dependent side relation and distance datum"], chronology: "A later collector or reconstructed channel cannot be combined with an early pool wall without a phase contact.", evidence: "The royal-pool setting is a comparison candidate. No inspected terminal connection establishes the full restored collector model.", open: "The connected collector itself and a dated reservoir–conduit–collector chain.", sourceIds: ["jericho-entry29", "jericho-inventory"] },
    { id: "damaged-name", label: "Damaged-name alternatives", attribution: "Milik; Eshel’s Hyrcania comparison", reading: "Retain the damaged Qe-name instead of translating it as a collecting installation.", requirements: ["An authenticated textual argument for the name", "The geographical setting that follows that reading", "The same independent feature and phase checks"], chronology: "A Jericho restoration does not exclude alternative settings, and a Jericho pool-offset test does not evaluate a different Hyrcania displacement model.", evidence: "The reviewed reading register retains name alternatives and explicitly marks the damaged word and restored geography.", open: "A reading that resolves the name and a source-controlled feature datum within the resulting setting.", sourceIds: ["jericho-entry29", "jericho-inventory"] },
  ] },
  { entryId: "31", summary: "The Doq association does not decide which installation the entry names. Keep each reading’s building and eastern relation coherent.", branches: [
    { id: "drying-place", label: "Drying place", attribution: "Puech 2006 p. 192; 2015 p. 67", reading: "The eastern corner of a spreading/drying place at Doq.", requirements: ["An installation whose drying function is documented", "Its eastern corner", "The contemporary surface for the seven-cubit digging instruction"], chronology: "A Hasmonean fortress date cannot date a separate drying installation or its use.", evidence: "Earlier printed-plate inspection leans toward this reading. No authenticated original-photo target or corresponding drying installation is established.", open: "A registered, legible VII 11 original and a source-supported installation with the required corner and phase.", sourceIds: ["doq-reading", "photo-audit", "doq-plan"] },
    { id: "guard-post", label: "Guard post", attribution: "Milik 1962 D19 p. 292; Lefkovits 2000 pp. 232–235", reading: "The eastern corner of a guard post, or a corner of the eastern guard post.", requirements: ["A documented guard post", "The retained corner/building attachment of eastern", "A securely dated corner and ancient ground datum"], chronology: "The broad fortress setting does not establish the guard post’s construction or accessible-use interval.", evidence: "A summit fortress is compatible context. Its existence cannot resolve the disputed landmark word or designate its eastern edge as a building corner.", open: "The reading, modifier attachment and a dated plan of the required building.", sourceIds: ["doq-reading", "doq-plan", "photo-audit"] },
  ] },
  { entryId: "49", summary: "Outlet/Siloam, baths/Raḥil and water-closet/Jehu impose different geographical and functional requirements. The photographed basin is contextual evidence, not a merged interpretation.", branches: [
    { id: "outlet-siloam", label: "Outlet / Siloam", attribution: "Puech 2015 pp. 85–86, 91–93", reading: "A water outlet with a reading-dependent Siloam association and a trough/gutter relation.", requirements: ["The disputed letter and supplied genitive", "A matching outlet and terminal installation", "The required under-feature relation in one phase"], chronology: "L103’s built masonry conditionally excludes it under the strict hollowed-stone model. A broader gutter interpretation remains unresolved; its receiver-floor and insertion dates require their own contacts.", evidence: "The tunnel and pools offer a compatible hydraulic setting. Printed plates lean toward Puech; original target registration and the required trough remain unresolved.", open: "An authenticated X 15–16 original and a dated, physically identified trough or outlet relation.", sourceIds: ["siloam-readings", "photo-audit", "siloam-test"] },
    { id: "displayed-baths", label: "Base text · baths / Raḥil?", attribution: "Current project transcription; compare Milik’s bath models", reading: "The displayed base text reads a basin(?) of the bathhouse(?) of Raḥil(?). Milik 1960 instead associates baths with Siloah; that is an additional name hypothesis.", requirements: ["Evidence that the selected basin served the required bath function", "An independently justified name association", "A place under the pipe belonging to that same basin"], chronology: "Neither the receiver’s coin date nor general pool occupation dates establish a contemporary main-basin pipe and bathing floor.", evidence: "L103 is observed at the small receiver. The main-basin under-pipe model is not identifiable from the available plans and function evidence.", open: "A surveyed main-basin junction, structural underside and ancient floor, plus the function/name evidence required by the selected bath model.", sourceIds: ["siloam-readings", "siloam-plan", "siloam-test"] },
    { id: "water-closet-jehu", label: "Water closet / Jehu", attribution: "Lefkovits 2000 pp. 352–354", reading: "A pool associated with a water closet and Jehu, without a Siloam place name.", requirements: ["The retained installation and personal-name reading", "A documented corresponding function", "An independent locality argument"], chronology: "A compatible date for a Siloam pool does not establish the function or locality of this branch.", evidence: "The edition alternative is retained. The Siloam label and photographed steps do not independently support its locality.", open: "A defensible reading and feature-specific function/locality evidence.", sourceIds: ["siloam-readings", "photo-audit"] },
  ] },
  { entryId: "60", summary: "Pit location, opening character and tomb relation vary across the retained registry. An alternative reading changes what must be observed; it supplies no new photograph or feature identification.", branches: [
    { id: "RB-M", label: "North-facing opening", attribution: "Milik branch in the reviewed registry", reading: "A pit north of Koḥlit, with a north-facing opening and tombs at its mouth.", requirements: ["An independently justified Koḥlit anchor", "A dated northern pit", "A defined side opening and facing direction", "Contemporaneous accessible tomb mouths at its mouth"], chronology: "A vertical shaft has no facing azimuth until a side entrance is defined. Graves cut by later pits do not establish contemporary access.", evidence: "Kenyon reports northern pits and graves as distinct features. The required mouth relation and contemporaneity remain unknown.", open: "A dated pit-mouth / tomb-mouth relation; the source registry’s retained reading requires an opening direction as well.", sourceIds: ["kohlit-readings", "jericho-graves", "jericho-succession"] },
    { id: "RB-P", label: "Concealed opening", attribution: "Puech branch in the reviewed registry", reading: "A pit north of Koḥlit, with a concealed opening and tombs at its mouth.", requirements: ["A dated northern pit", "Evidence for the concealed-opening property", "A contemporary tomb-at-mouth relationship"], chronology: "This branch imposes no opening azimuth. Modern burial or obscuration alone does not establish ancient concealment.", evidence: "The same northern-sector records cannot resolve concealment, mouth position or joint accessibility.", open: "A source-controlled ancient opening and tomb relation. XII 10’s protected image test remains pending.", sourceIds: ["kohlit-readings", "jericho-graves", "jericho-succession"] },
    { id: "RB-B", label: "Buried · no required tombs", attribution: "Separate retained project-registry branch", reading: "A buried reading that does not require a tomb landmark; the opening interpretation remains unresolved.", requirements: ["A justified Koḥlit anchor", "The specified northern pit and use phase", "The opening interpretation required by the defended reading"], chronology: "A missing tomb cannot be scored as a failure for a branch that does not require one.", evidence: "The saved relationship comparisons retain this branch without borrowing the north-facing or concealed predicate.", open: "The defended reading and dated pit identity remain unresolved.", sourceIds: ["kohlit-readings"] },
    { id: "RB-L", label: "Pit at Janoaḥ", attribution: "Lefkovits 2000 pp. 425–426, as attributed in the registry", reading: "A pit at reading-dependent Janoaḥ / Yanun, tested separately from the Koḥlit anchor.", requirements: ["Authentication of the Janoaḥ reading", "An independently located Yanun pit", "The retained north-of-Koḥlit and tomb relations"], chronology: "A Yanun place proposal cannot substitute the Koḥlit anchor’s coordinate for a pit coordinate.", evidence: "The registry keeps Yanun features unassigned. No qualifying XII 10 target image has been opened under the frozen protocol.", open: "The protected XII 10 letter test and a source-supported pit location/phase.", sourceIds: ["kohlit-readings"] },
  ] },
];
