"""Author the reviewed model; run only when explicitly revising this specification."""
import json
from pathlib import Path

BASE = 'research/agent_review_2026-10-07/'
SOURCES = [
 {'id':'relationships-text-core','title':'Reviewed Koḥlit edition relationships','citation':'Entry 11, II 13–15; Puech 2015 pp. 13–14 n. 49; reviewed e11-kohlit / e19-kohlit reading records','repo_path':'text/readings.json','inspection':'derived'},
 {'id':'relationships-text-e60','title':'Reviewed Entry 60 reading and period registry','citation':'XII 10–13; Milik 1960 item 64; Puech 2006 p. 175 n. 49 / 2015 pp. 13–14 n. 49; Lefkovits 2000 pp. 425–426, as attributed in registry v2','repo_path':BASE+'wave2/W2B_model_v1/registry_v2_entry60.json','inspection':'derived'},
 {'id':'relationships-text-restored','title':'Puech Entry 15–16 restoration audit','citation':'Puech 2015 pp. 48–51, especially pp. 49–50 and n. 193; IV 1–5','repo_path':'research/measurements/cycle7/kohlit_pool.md','inspection':'already_inspected'},
 {'id':'relationships-dorrell','title':'Dorrell, The Spring at Jericho from Early Photographs','citation':'PEQ 125 (1993), pp. 95–97, 110–112; Figs. 1–4, 20–21 (pp. 98–99, 107)','repo_path':BASE+'followup/A_jericho_spring_reservoir.md','inspection':'already_inspected','original_campaign':'Historical photographs 1856–1954 compiled by Dorrell; not independent field corroborations'},
 {'id':'relationships-kenyon-II','title':'Kenyon, Excavations at Jericho II','citation':'1965 pp. 169, 276–277 / Fig. 137.2, 516, 536–537, 539–544; distribution Fig. 91 p. 168','repo_path':BASE+'followup/C_kenyon_jericho_II_and_kh_yanun.md','inspection':'already_inspected','original_campaign':'Kenyon Jericho expedition, 1952–1958'},
 {'id':'relationships-kenyon-III','title':'Kenyon, Excavations at Jericho III, Text','citation':'1981 pp. 173–174 / supplied PDF 207–208; supporting pp. 3–4, 119–121; separate E section and Plate 111b are not inspected','repo_path':BASE+'followup/C_kenyon_jericho_II_and_kh_yanun.md','inspection':'already_inspected','original_campaign':'Kenyon Jericho expedition, 1952–1958'},
 {'id':'relationships-zohar','title':'Zohar, Tell Marjame / Ein Samiya','citation':'IEJ 30 (1980), pp. 219–220; HA 76 (1981), p. 19 / supplied PDF 20; same December 1979–January 1980 excavation','repo_path':BASE+'followup/B_kh_el_marjama.md','inspection':'already_inspected','original_campaign':'Zohar rescue excavation, December 1979–January 1980'},
 {'id':'relationships-mazar','title':'Mazar, Excavations at Khirbet Marjameh','citation':'IEJ 45 (1995), pp. 85–87, 95; Fig. 1 p. 86 (spring / tell context)','repo_path':BASE+'followup/B_kh_el_marjama.md','inspection':'already_inspected'},
 {'id':'relationships-highlands','title':'Highlands of Many Cultures, reviewed site entries','citation':'1997 pp. 732–735 (tell, church and Kh. Samiya), 741 (north/NNE Bronze Age tombs), 821–822 and 828–831 (Yanun / Kh. Yanun)','repo_path':BASE+'followup/B_kh_el_marjama.md','inspection':'already_inspected'},
 {'id':'relationships-yanun','title':'Reviewed Kh. Yanun / Yanun village record','citation':'Highlands of Many Cultures (1997), pp. 821–822, 828–831; Lefkovits 2000 pp. 425–426 only through the reviewed registry','repo_path':BASE+'followup/C_kenyon_jericho_II_and_kh_yanun.md','inspection':'already_inspected'},
 {'id':'relationships-kallai','title':'Kallai rock-cut-pool source dependency','citation':'Kallai chapter in Kochavi (ed.), Judaea, Samaria and the Golan: Archaeological Survey 1967–1968 (1972), pp. 172–173; sites 65–66 context remains unread','repo_path':BASE+'followup/B_kh_el_marjama.md','url':'https://www.nli.org.il/he/books/NNL_ALEPH990019622650205171/NLI','inspection':'not_inspected'},
]

observations=[]
def fact(suffix,feature,relation,asserted,sources,note,target=None,kind='observed',**meta):
 value={'reference_feature_id':target,'asserted':asserted}
 observations.append({'id':'relationships-'+suffix,'feature_id':feature,'property':relation,'value':value,'evidence_kind':kind,'source_ids':sources,'exposure':'derived' if kind=='inference' else 'already_inspected','note':note,**meta})
def chronology(suffix,feature,sources,note,**value):
 observations.append({'id':'relationships-'+suffix,'feature_id':feature,'property':'chronology','value':{'reference_feature_id':None,'secure_earliest_construction_year':None,'secure_last_accessible_year':None,'dated_accessible_interval':None,**value},'evidence_kind':'published_reconstruction','source_ids':sources,'exposure':'already_inspected','note':note})

fact('historical-east','jericho-historical-basin','east_of',True,['relationships-dorrell'],'The historical basin is documented at the spring on the tell’s eastern foot. This is a qualitative source relation; no basin-to-anchor surveyed bearing is asserted.','jericho-tell',reference_frame='Dorrell’s qualitative spring/tell description; unregistered historical photographs')
fact('modern-east','jericho-reservoir-1898','east_of',True,['relationships-dorrell'],'The 1898 reservoir stands at the eastern-foot spring. Its position cannot supply an earlier pool state.','jericho-tell',reference_frame='Dorrell’s qualitative spring/tell description')
chronology('historical-basin-chronology','jericho-historical-basin',['relationships-dorrell'],'The irregular basin is observed in nineteenth-century records; its construction and early accessible-use interval are unknown. Do not backdate it from the adjacent ancient curved wall.',first_documented_state_year=1856)
chronology('modern-reservoir-chronology','jericho-reservoir-1898',['relationships-dorrell'],'Dorrell p. 111 dates extension of the mill-pool into the present reservoir to 1898. This is a separate physical/state assignment from the historical irregular basin.',secure_earliest_construction_year=1898)
chronology('springwall-chronology','jericho-springhouse-wall',['relationships-dorrell'],'Late Roman / Byzantine is Dorrell’s architectural opinion, without sealed finds dating the lowest course. It does not date the separate basin.',attributed_date='very probably late Roman or Byzantine',dating_basis='architectural opinion; no sealed construction date')
fact('ns1-north','jericho-cistern-ns1','north_of',True,['relationships-kenyon-II'],'NS1 is reported on the camp outskirts toward Khirbet Mefjar, north of the tell. No plan or surveyed cistern-mouth position was made.','jericho-tell',reference_frame='Kenyon II qualitative location; no mouth coordinate')
chronology('ns1-chronology','jericho-cistern-ns1',['relationships-kenyon-II'],'Kenyon labels NS1 a Roman cistern and reports Herodian lamps / comparison finds. Its construction, ancient mouth and independently dated accessible-use interval are not documented.',attributed_date='Roman',dating_basis='excavator attribution / cistern assemblage')
fact('d9-north','jericho-shaft-d9','north_of',True,['relationships-kenyon-II'],'Area D is inferred to be in the sector north of the tell from the reviewed distribution map. This source-plan sector inference is not a measured shaft-mouth bearing.','jericho-tell',kind='inference',reference_frame='Fig. 91 p. 168 qualitative sector interpretation; not registered')
chronology('d9-chronology','jericho-shaft-d9',['relationships-kenyon-II'],'A Roman burial cuts into the side of a Middle Bronze shaft. The older shaft’s dated accessibility / opening arrangement in the selected early window remains unknown.',attributed_date='Middle Bronze shaft with Roman burial reuse',dating_basis='relative shaft/reuse description')
fact('d9-burial-position','jericho-shaft-d9','burial_in_side_of_shaft',True,['relationships-kenyon-II'],'D9’s burial is at a recessed ledge at the base / side of the older shaft. This cannot be substituted for tombs at a separately defined pit mouth.')
fact('graves-north','jericho-north-graves','north_of',True,['relationships-kenyon-III'],'About eighteen graves are reported on the north slope / Trench II, mostly toward its northern end; not every grave has an individual mapped mouth.','jericho-tell',reference_frame='Trench II / Site O local excavation coordinates; no national datum')
chronology('graves-chronology','jericho-north-graves',['relationships-kenyon-III','relationships-kenyon-II'],'Kenyon assigns the on-tell graves to the first century CE by grave-type comparison. There are no offerings in this scope and no dated jointly accessible grave/pit-mouth interval.',attributed_date='first century CE',estimated_typological_interval=[1,100],dating_basis='type comparison; no grave-associated dating finds in III 173–174')
fact('quarries-north','jericho-later-quarry-pits','north_of',True,['relationships-kenyon-III'],'Numerous later pits occupy much of the northern trench end. Their individual mouths have no national-datum position.','jericho-tell',reference_frame='Trench II / Site O local frame')
chronology('quarries-chronology','jericho-later-quarry-pits',['relationships-kenyon-III'],'The phase-lxxvii quarry pits cut phase-lxxvi graves and are rubble-filled. They have no secure absolute date; later-than-grave alone is not an early-window failure.',relative_after_feature='jericho-north-graves',attributed_function='brickearth quarries')
fact('quarries-later-phase','jericho-later-quarry-pits','constructed_same_phase_as',False,['relationships-kenyon-III'],'The pits truncate the graves and belong to later phase lxxvii, after grave phase lxxvi. This rejects same-phase construction only; it does not settle later joint accessibility.','jericho-north-graves',phase={'subject':'lxxvii / Stage XXV','object':'lxxvi / Stage XXIV'})
fact('quarries-co-use','jericho-later-quarry-pits','coexisted_with',None,['relationships-kenyon-III'],'Published truncation establishes sequence, not whether a usable later opening and surviving graves were jointly accessible within an early window.','jericho-north-graves')
fact('crypt-west','samiya-crypt-basin','east_of',False,['relationships-zohar','relationships-highlands','relationships-mazar'],'On this named crypt-basin/spring assignment, the church is at the western foot and the spring southwest of the tell. This conditional crosswalk contradicts east-of-tell; it does not locate Kallai’s separate pool.','marjama-tell',kind='inference',reference_frame='Published qualitative church/spring/tell crosswalk; no validated bearing')
chronology('crypt-chronology','samiya-crypt-basin',['relationships-zohar','relationships-highlands'],'The basin was beneath a Byzantine church crypt; the church was later destroyed. The basin itself has no separate construction date or early-use interval.',associated_structure_date='Byzantine church; basin date unknown')
fact('kallai-location','marjama-kallai-pool','east_of',None,['relationships-kallai'],'Kallai’s original pp. 172–173 remain unread and the reported rock-cut pool remains unlocated. HA 76 p. 19 describes settlement excavation and supplies no pool or bearing.','marjama-tell',kind='inference')
chronology('kallai-chronology','marjama-kallai-pool',['relationships-kallai','relationships-zohar'],'No dated pool phase or physical crosswalk to the crypt basin is established; Kallai’s native pool pages remain unread.')
fact('samiya-bronze-north','samiya-north-bronze-tombs','north_of',True,['relationships-highlands','relationships-mazar'],'Dhahr Mirzbaneh’s shaft tombs are documented north/NNE of the tell and attributed to Intermediate Bronze / Middle Bronze. Their ancient mouths and later accessibility are unobserved here.','marjama-tell',reference_frame='Published site-level qualitative location')
chronology('samiya-bronze-chronology','samiya-north-bronze-tombs',['relationships-highlands','relationships-mazar'],'Bronze Age construction does not establish or exclude survival/accessibility in the early Roman window. There is no dated pit-mouth relation to this group.',attributed_date='Intermediate Bronze / Middle Bronze; later accessible use unknown')
fact('hydraulics-location','samiya-hydraulic-system','east_of',None,['relationships-highlands'],'Roman–Byzantine dams and aqueducts are reported at Kh. Samiya south/SE of the tell. No surveyed contact to Kallai’s pool or the church crypt basin is established.','marjama-tell',kind='inference')
fact('yanun-pit-coverage','yanun-site','reported_pit_count',None,['relationships-yanun'],'The inspected Kh. Yanun site record describes no pit/cistern/tomb. This is report coverage, not an archaeological absence; a pit role remains unassigned.')

core=['pool-east','pool-period','pool-north-corner','pit-north','pit-period']
readings=[
 {'id':'RB-M','label':'Milik: north-facing opening','summary':'Pit north of Koḥlit; north-facing opening; tombs at its mouth. A vertical shaft has no facing azimuth until a side entrance is defined.','predicate_ids':core+['opening-north','graves-at-mouth','joint-accessibility'],'source_ids':['relationships-text-e60']},
 {'id':'RB-P','label':'Puech: concealed opening','summary':'Pit north of Koḥlit; concealed opening; tombs at its mouth. No opening azimuth is imposed.','predicate_ids':core+['opening-concealed','graves-at-mouth','joint-accessibility'],'source_ids':['relationships-text-e60']},
 {'id':'RB-B','label':'Buried: no required tombs','summary':'The project registry retains a separate buried reading without a required tomb landmark; no missing tomb becomes a scored failure. The opening interpretation remains unresolved.','predicate_ids':core,'source_ids':['relationships-text-e60']},
 {'id':'RB-L','label':'Lefkovits: pit at Janoaḥ','summary':'Pit at reading-dependent Janoaḥ / Yanun; north of Koḥlit is tested separately. The Koḥlit anchor is not substituted for a Yanun pit coordinate.','predicate_ids':core+['pit-at-yanun','graves-at-mouth','joint-accessibility'],'source_ids':['relationships-text-e60','relationships-yanun']},
]
windows=[{'id':'early','label':'50 BCE–70 CE','years':[-50,70],'status':'exploratory project window','source_ids':['relationships-text-e60']}, {'id':'extended','label':'50 BCE–135 CE','years':[-50,135],'status':'exploratory extended project window','source_ids':['relationships-text-e60']}]

def pred(id,label,relation,subject,object=None,sources=None,missing=None,**extra):
 return {'id':id,'label':label,'relation':relation,'subject':subject,'object':object,'source_ids':sources or ['relationships-text-e60'],'missing_detail':missing or 'No source-controlled observation of this relation is available.','required':True,**extra}
predicates=[
 pred('pool-east','Pool east of the Koḥlit anchor','east_of','pool','anchor',['relationships-text-core']),
 pred('pool-period','Pool accessible in the selected early window','exists_during','pool',sources=['relationships-text-core','relationships-text-e60']),
 pred('pool-north-corner','Ancient pool has the specified northern corner','has_ancient_northern_corner','pool',sources=['relationships-text-core'],missing='Historical basin descriptions and modern walls do not define a dated ancient northern-corner datum.'),
 pred('pit-north','Pit north of the Koḥlit anchor','north_of','pit','anchor'),
 pred('pit-period','Pit accessible in the selected early window','exists_during','pit'),
 pred('opening-north','Defined side opening faces north','opens_toward_north','pit',missing='No defined side opening and source-controlled facing direction are supplied; a vertical shaft is not assigned an azimuth.'),
 pred('opening-concealed','Opening was concealed in the relevant state','opening_concealed','pit',missing='No phase-controlled cover, blocking or concealment observation is supplied; later rubble is not automatically the ancient concealed opening.'),
 pred('graves-at-mouth','Tombs at the pit mouth','at_mouth_of','graves','pit',missing='Graves and a pit in the same northern sector do not establish individual tomb mouths at this pit mouth. No metric proximity tolerance is invented.'),
 pred('joint-accessibility','Pit mouth and graves jointly accessible','coexisted_with','pit','graves',missing='Independent feature dates and relative succession do not establish contemporaneous accessible mouths within the selected early window.'),
 pred('pit-at-yanun','Pit lies at reading-dependent Janoaḥ / Yanun','within','pit','route',['relationships-text-e60','relationships-yanun'],missing='No named Yanun pit, its outline, date or mouth is documented. Kh. Yanun and Yanun village are retained distinct site alternatives.'),
 pred('same-construction-phase','Quarry pits and graves share construction phase','constructed_same_phase_as','pit','graves',['relationships-kenyon-III']),
]

assignments=[]
def assign(id,label,anchor,pool,pit,graves,sources,reading_ids=None,**extra):
 assignments.append({'id':id,'label':label,'roles':{'anchor':anchor,'pool':pool,'pit':pit,'graves':graves,'route':extra.pop('route',None)},'source_ids':sources,'reading_ids':reading_ids or ['RB-M','RB-P','RB-B'],'status':'exploratory assignment; no feature identity confirmed',**extra})
assign('jericho-historical-ns1','Jericho historical basin + NS1','jericho-tell','jericho-historical-basin','jericho-cistern-ns1','jericho-north-graves',['relationships-dorrell','relationships-kenyon-II','relationships-kenyon-III'])
assign('jericho-modern-ns1','Jericho 1898 reservoir + NS1','jericho-tell','jericho-reservoir-1898','jericho-cistern-ns1','jericho-north-graves',['relationships-dorrell','relationships-kenyon-II','relationships-kenyon-III'])
assign('jericho-d9','Jericho historical basin + D9','jericho-tell','jericho-historical-basin','jericho-shaft-d9','jericho-north-graves',['relationships-dorrell','relationships-kenyon-II','relationships-kenyon-III'])
assign('jericho-quarry','Jericho historical basin + later quarry pits','jericho-tell','jericho-historical-basin','jericho-later-quarry-pits','jericho-north-graves',['relationships-dorrell','relationships-kenyon-III'])
assign('samiya-kallai','Marjama unlocated Kallai pool + northern shaft-tomb sector','marjama-tell','marjama-kallai-pool',None,'samiya-north-bronze-tombs',['relationships-kallai','relationships-highlands','relationships-mazar'])
assign('samiya-crypt','Marjama southwest crypt basin + northern shaft-tomb sector','marjama-tell','samiya-crypt-basin',None,'samiya-north-bronze-tombs',['relationships-zohar','relationships-highlands','relationships-mazar'])
assign('yanun-jericho-anchor','Janoaḥ / Yanun pit unassigned; Jericho Koḥlit anchor','jericho-tell','jericho-historical-basin',None,None,['relationships-text-e60','relationships-yanun'],['RB-L'],route='yanun-site')
assign('yanun-marjama-anchor','Janoaḥ / Yanun pit unassigned; Marjama Koḥlit anchor','marjama-tell','marjama-kallai-pool',None,None,['relationships-text-e60','relationships-yanun'],['RB-L'],route='yanun-site')

supplementary_graph=[
 {'id':'relationships-e15-restored-north','entry':'15','lines':'IV 1–2','relation':'north_of','subject_role':'great_cistern','object_role':'anchor','restored':True,'status':'unknown','feature_assignment':None,'source_ids':['relationships-text-restored'],'note':'The northern Koḥlit link is restored and north may attach to the cistern/pillar relation. NS1 is not automatically the great cistern with a northern pillar.'},
 {'id':'relationships-e16-restored-feeds','entry':'16','lines':'IV 3–5','relation':'feeds','subject_role':'conduit','object_role':'restored_pool','restored':True,'status':'unknown','feature_assignment':None,'source_ids':['relationships-text-restored'],'note':'Puech restores a pool destination. Koḥlit association is contextual and equating this destination to Entry 11’s pool is a separate unverified alias hypothesis.'},
 {'id':'relationships-e19-eastern-pit','entry':'19','lines':'IV 11–12','relation':'east_of','subject_role':'pit','object_role':'another_pit','restored':False,'status':'unknown','feature_assignment':None,'source_ids':['relationships-text-core'],'note':'Eastern selects among pits; no second pit datum is defined. A north-of-site relation cannot resolve eastern among pits. Allegro’s no-place-name variant remains outside this core pilot.'},
]
model={'schema_version':1,'sources':SOURCES,'features':[{'id':'samiya-north-bronze-tombs','name':'Dhahr Mirzbaneh northern shaft-tomb field','kind':'tomb_group','site':'Ein Samiya / Kh. el-Marjama','geometry':None}],'observations':observations,'readings':readings,'windows':windows,'predicates':predicates,'assignments':assignments,'graph_roles':[{'id':'anchor','label':'Koḥlit anchor'},{'id':'pool','label':'Entry 11 pool'},{'id':'pit','label':'Entry 60 pit'},{'id':'graves','label':'Tomb mouths'},{'id':'route','label':'Reading-dependent Janoaḥ'}],'supplementary_graph':supplementary_graph,'limits':[
 'All inputs were already exposed in prior project work; none is an unused prediction or an independent confirmatory test.',
 'The finite roster is selected for implementation and does not enumerate all Koḥlit proposals, regional pools, shafts or caves. Regional eligibility and denominator remain unknown.',
 'Direction checks use explicitly attributed qualitative source statements or marked inference. They are not measured bearings, geographic outlines or tolerance-calibrated fits.',
 'Separate construction phases can overlap in later usable states; relative pit/grave sequence does not establish or disprove early joint accessibility.',
 'Known historical photographs cannot backdate the irregular basin or replace the securely 1898 reservoir with an ancient state.',
 'Edition branches, Koḥlit anchors, pool/shaft identities and modern geographic positions remain separate hypotheses. Unknowns are never scored as misses.',
 'Opening azimuth, mouth proximity, great-cistern identity, pillar position, conduit-to-pool identity and all phase-specific measuring datums remain unresolved. No new distances or deposits are generated.',
 'The module imports source pointers, not source images; original reuse limits and parked acquisition remain unchanged.',
]}
Path(__file__).with_name('model.json').write_text(json.dumps(model,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
