# -*- coding: utf-8 -*-
"""Prediction records, part A (entries 1-38 except Kohlit entries).

Every factual statement in `evidence` is attributed. Most attributions are
second-hand through the quadrin/CopperScroll repository files shipped in
cs/shared and cs/repo (cited as 'via <file>'). `inference` is this registry's
own reasoning. Coordinates are NOT written here: build_registry.py copies them
from shared/places.json by place_id, so no coordinate is typed by hand.
"""

R = []

def rec(**kw):
    R.append(kw)

# ---------------------------------------------------------------- entry 1
rec(id="P01-A", entry="1", branch="Achor = Wadi Nuweiʿimeh; ruin = Ḥoreibbeh near later Chorembe monastery",
    reading_assumed="ḥryb(ʾ)h 'little ruin' (yod) read as the place Ḥoreibbeh; עכור = Achor; 40 cubits (unit word after 'cubits', Puech)",
    reading_editions=["Milik 1960, 1962", "Puech 2006, 2015"],
    reading_status="disputed (waw/yod in the ruin word; עכור vs עבור 'go past'; 40 vs 41 vs deleted word)",
    place_id="nuweimeh",
    feature_type="ruin with a stair that 'goes in toward the east'",
    feature_detail="A ruined building (already a ruin, or later known as Ḥoreibbeh/Chorembe) with a built or rock-cut flight of steps whose line of entry runs eastward.",
    orientation="stair axis runs (enters) toward the east; tolerance not stated by the text — score with ±45° of true east and report the measured azimuth",
    measures=[{"cubits": 40, "edition": "Puech 2006", "type": "distance along/under the stair (unresolved: distance vs depth)"},
              {"cubits": 41, "edition": "Lefkovits 2000", "type": "same"}],
    location="Within the Wadi Nuweiʿimeh drainage NE/N of Jericho; Milik and Puech tie the ruin name to the monastery of Chorembe near Kh. el-Mafjar (no gazetteer coordinate for that monastery; none asserted here).",
    confirm="L2: a ruin with an east-running stair, standing or built before 135 CE (preferably before 70 CE), documented in the valley near the Chorembe/Kh. el-Mafjar area. L3: a period cut/cavity 17.8–21.0 m (40 c.; 18.2–21.5 m for 41 c.) from the stair head or foot along its axis.",
    miss="Feature-level only: for a specific candidate ruin, the stair is securely dated after 135 CE with no earlier phase, or the 17.8–21.5 m axial band beyond both stair ends is excavated to sterile deposits/bedrock without any period cut. No area-level miss can follow from one excavation.",
    inconclusive="Undated stair; azimuth not recorded; band only partly excavated; ruin of uncertain identity with Chorembe.",
    report_extra=["stair azimuth (true north) and direction of descent", "elevations of top and bottom step and of the ancient surface at each end",
                  "chainage along the stair axis to the excavation limits", "identity argument linking the ruin to Chorembe/Ḥoreibbeh, if claimed"],
    priority="low", scorability="area-level (feature-level only if a ruin-with-east-stair is proposed)",
    evidence=[("Milik and Puech read a yod ('little ruin') and take it as Ḥorebbeh, later the monastery of Chorembe near Kh. el-Mafjar; Lefkovits, Lurie, Muchowski read a waw.", "Milik 1960 pp. 143–144; DJD III D4 p. 263; Puech 2006 p. 179; 2015 p. 26 — via shared/readings.json e1-ruin"),
              ("No published report describes a ruin with steps that fits.", "via shared/readings.json e1-ruin; phase5_summary §5"),
              ("Achor: Milik/Puech follow the late tradition (Eusebius, north of Jericho); Allegro/Eshel prefer the Buqeia.", "via shared/readings.json e1-achor")],
    inference=("Prediction is deliberately weak: the text gives a direction and a long distance but no fixed origin.", "low"),
    sources=["Milik DJD III D4 p. 263", "SWP III p. 226", "ʿAtiqot 41 (Aronshtam) pp. 91, 99"])

rec(id="P01-B", entry="1", branch="Achor = el-Buqeiʿah (Iron Age 'Valley of Trouble')",
    reading_assumed="עכור = Achor located in the Buqeia; ruin word either reading; 40/41 cubits",
    reading_editions=["Allegro (via Lefkovits p. 29)", "Eshel 2002 (CSS ch. 6)"],
    reading_status="disputed (as P01-A)", place_id="buqeia",
    feature_type="ruin with a stair that 'goes in toward the east'",
    feature_detail="As P01-A, but sought among the Iron Age and later ruins of the Buqeia plateau.",
    orientation="as P01-A", measures=[{"cubits": 40, "edition": "Puech 2006", "type": "distance (unresolved)"}, {"cubits": 41, "edition": "Lefkovits 2000", "type": "distance (unresolved)"}],
    location="Anywhere in the Buqeia (gazetteer area ~5 km); no finer target.",
    confirm="As P01-A (L2/L3), with the ruin in the Buqeia.",
    miss="Feature-level only, as P01-A.", inconclusive="As P01-A.",
    report_extra=["stair azimuth", "phase of the stair relative to Iron Age vs Hellenistic–Roman occupation"],
    priority="low", scorability="area-level",
    evidence=[("Allegro and Eshel place Achor in the Buqeia.", "via shared/readings.json e1-achor (Allegro via Lefkovits p. 29; Eshel CSS ch. 6)")],
    inference=("Competing geography; kept as a branch so a Buqeia find cannot be scored as support for P01-A.", "low"),
    sources=["Eshel 2002, Copper Scroll Studies ch. 6"])

# ---------------------------------------------------------------- entry 9
common9 = dict(entry="9", place_id="jer_east_gate",
    feature_type="cistern with a channel (מזקא), 'opposite' the East Gate",
    orientation="'opposite' (נגד) the gate: on or near the gate axis; whether inside (west) or outside (east) the enclosure is unresolved",
    report_extra=["position of the Herodian-period East Gate threshold used as origin (Golden Gate vs another gate line)",
                  "horizontal distance and azimuth from that threshold to the cistern mouth and to the nearest cistern wall",
                  "channel inlet/outlet position and invert levels", "plaster type and construction phase of the cistern",
                  "survey/coverage map of the band 5–12 m from the gate on both sides (GPR or excavation), so absence can be scored"],
    priority="medium", scorability="feature-level (realistically only by non-invasive survey or chance exposure)",
    sources=["Warren 1871 pp. 153–158, 204 ff.", "Warren 1884 PEF Plans Pl. VI", "Puech 2006 p. 184", "Lefkovits 2000 p. 127"])
rec(id="P09-A", branch="19 cubits (Lefkovits); cistern and channel one entry",
    reading_assumed="רחוק אמות תשע עסרה '19 cubits away'; ובמזקא שבו 'and in its channel' belongs to the same cistern",
    reading_editions=["Lefkovits 2000 pp. 126–127"], reading_status="numeral disputed (19 Lefkovits / 15 Puech); entry division disputed (Milik splits II 9)",
    feature_detail="A cistern whose channel is part of it, located 19 cubits from the East Gate of the Temple enclosure.",
    measures=[{"cubits": 19, "edition": "Lefkovits 2000", "type": "horizontal distance from the gate"}],
    location="On the gate axis 8.5–10.0 m from the Herodian East Gate threshold (Golden Gate position assumed).",
    confirm="L2: a cistern with a channel, existing before 70 CE, whose mouth or nearest wall lies 8.5–10.0 m (19 c.) from the Herodian East Gate threshold, roughly on its axis. L4: metal vessels in the cistern and a deposit in its channel.",
    miss="A complete geophysical or excavated coverage of both sides of the gate axis between 6 and 12 m from the threshold showing no cistern; OR proof that the Herodian East Gate stood elsewhere AND the same coverage at that gate is negative.",
    inconclusive="Partial coverage; gate position unresolved; cistern found but undated.",
    evidence=[("On Warren's Plate VI no recorded cistern lies within about 18 m of the Golden Gate; the nearest (No. 15) is 30.0 m away; only open mouths were recorded and 30–40 ft of debris lay in front of the gate.", "via shared/feature_constraints.csv (Warren 1884 PEF Plans Pl. VI; Warren 1871 pp. 154–156)"),
              ("Lefkovits reads 19 cubits, Puech 15.", "via shared/readings.json (entry 9, II 8)")],
    inference=("The prediction therefore requires a cistern not on Warren's plan: a recorded-cistern match already fails, so only a new observation can confirm.", "medium"),
    **common9)
rec(id="P09-B", branch="15 cubits (Puech)",
    reading_assumed="15 cubits; one entry", reading_editions=["Puech 2006"], reading_status="numeral disputed",
    feature_detail="As P09-A at 15 cubits.",
    measures=[{"cubits": 15, "edition": "Puech 2006", "type": "horizontal distance from the gate"}],
    location="On the gate axis 6.7–7.9 m from the Herodian East Gate threshold.",
    confirm="As P09-A with the 6.7–7.9 m window.", miss="As P09-A (coverage 5–10 m).", inconclusive="As P09-A.",
    evidence=[("Puech reads 15 cubits.", "via shared/readings.json (entry 9, II 8)")],
    inference=("Same feature model as P09-A; distance window differs.", "medium"), **common9)

# ---------------------------------------------------------------- entry 10
rec(id="P10-A", entry="10", branch="Temple/city east wall near the East Gate",
    reading_assumed="בבור שתחת החומא מן המזרח בשן הסלע … ביאתו תחת הסף הגדול",
    reading_editions=["Milik 1962 D52 p. 272", "Lefkovits 2000 p. 130", "Puech 2006 p. 184"],
    reading_status="letters agreed; wall = city wall (Lefkovits) or rampart (Puech, Milik); בדין 'bars' vs כדין 'pitchers' does not affect place",
    place_id="jer_east_gate",
    feature_type="rock-cut cistern beneath the eastern wall, in a bedrock spur, entered from below a monumental threshold",
    feature_detail="A cistern under the line of the eastern wall, cut into a projecting rock spur; its entrance (or the cache) lies under 'the great threshold'.",
    orientation="on the east side of the wall", measures=[],
    location="Under or against the eastern enclosure/city wall near the East Gate (gazetteer ~50 m).",
    confirm="L2: a pre-70 CE cistern cut in a bedrock spur directly beneath the eastern wall foundation, with access passing under a large threshold stone (gate or postern). L4: silver in jars/bars inside.",
    miss="Feature-level: the only cistern(s) under the eastern wall near the gate are shown to post-date 135 CE, or have no access under a threshold.",
    inconclusive="Cistern known only from mouths; threshold relation not recorded; undated.",
    report_extra=["relation of the cistern to the wall foundation courses (under / beside / cut later)", "bedrock profile showing the spur",
                  "location, dimensions and phase of any threshold stone above the access", "date of the wall course above the cistern"],
    priority="medium", scorability="feature-level (non-invasive or chance exposure)",
    evidence=[("Rock scarps and undated cisterns are reported along the eastern wall.", "via shared/phase5_archaeology_index.csv (Warren 1871 pp. 135–141, 204 ff.)"),
              ("Milik: a rocky projection under the east rampart.", "Milik 1962 D52 p. 272 via shared/readings.json")],
    inference=("Threshold + spur + under-wall is a tight conjunction; a single exposed example would be highly diagnostic.", "medium"),
    sources=["Warren 1871 pp. 135–141, 204 ff.", "Milik DJD III p. 272"])

# ---------------------------------------------------------------- entry 17
rec(id="P17-A", entry="17", branch="Puech 'two cavities'; Achor = Wadi Nuweiʿimeh; pair = Cave V/49 + neighbour V/48",
    reading_assumed="שני הכינין 'the two cavities'; באמצען 'midway between them'; dig 3 cubits",
    reading_editions=["Puech 2006 pp. 186–187", "Høgenhaven 2020 p. 62 n. 32"],
    reading_status="landmark noun disputed (cavities / tamarisks / buildings); engraved עכון corrected to Achor by all",
    place_id="nuweimeh",
    feature_type="pair of contemporaneous rock cavities with a dug point midway between them",
    feature_detail="Under the cavity reading, the first concrete pair is Cave V/49 (dwelling/storage, 1st c. BCE–First Revolt) and its neighbouring dwelling cave V/48 reached by a path (Eisenberg 2002 p. 120).",
    orientation="none stated", measures=[{"cubits": 3, "edition": "Puech 2006", "type": "digging depth"}],
    location="Midpoint between the two cave entrances (also test chamber-centre and path-midpoint definitions); printed-grid spacing of V/48–V/49 about 71 m (0–141 m).",
    confirm="L2: both caves shown to be in use or open in the 1st c. BCE–1st c. CE and no closer comparable pair; L3: a period cut or cavity 1.34–1.58 m (3 c.) below the ancient surface at one of the declared midpoints (tolerance ±5% of spacing).",
    miss="For this pair: all three declared midpoints excavated to ≥1.6 m below the ancient surface (or to bedrock) through undisturbed pre-Roman sediment; or one cave shown to have been opened only after 135 CE.",
    inconclusive="Spacing/entrances not surveyed; midpoint sediment disturbed by flood or looting; depth not reached.",
    report_extra=["surveyed entrance coordinates of both caves with datum and accuracy", "date of first opening/use of each cave",
                  "ancient surface level at the midpoint(s)", "sediment sequence to 1.6 m with dating"],
    priority="medium", scorability="feature-level",
    evidence=[("Eisenberg reports V/49 as a dwelling/food-storage cave used 1st c. BCE to the First Revolt, with a neighbouring dwelling cave (V/48) hewn in the Second Temple period.", "via shared/feature_constraints.csv and repo dok_achor_feature_tests.md (Eisenberg, ʿAtiqot 41, 2002 p. 120)"),
              ("V/48–V/49 spacing about 71 m (0–141 m) on the printed grid; no midpoint drawn.", "via shared/feature_constraints.csv")],
    inference=("A test of one pair only; many rival pairs exist, so a hit would need the deposit level (L3+) to matter.", "low-medium"),
    sources=["ʿAtiqot 41 (Aronshtam pp. 98, 101; Eisenberg p. 120; Sion pp. 80–81)", "Puech 2006 pp. 186–187"])
rec(id="P17-B", entry="17", branch="Lefkovits 'two buildings'",
    reading_assumed="הבתין 'the two buildings'; midway; dig 3 cubits", reading_editions=["Lefkovits 2000 pp. 162–164"],
    reading_status="disputed", place_id="nuweimeh",
    feature_type="two buildings with a dug point midway", feature_detail="Two standing buildings of the period in the Valley of Achor.",
    orientation="none", measures=[{"cubits": 3, "edition": "Lefkovits 2000 (depth assumed)", "type": "digging depth"}],
    location="Valley of Achor (Nuweiʿimeh or Buqeia); no pair proposed.",
    confirm="L2: two buildings of the period with a documented midpoint; L3: period cut at 1.34–1.58 m at the midpoint.",
    miss="Feature-level only.", inconclusive="Any pair without dating or midpoint excavation.",
    report_extra=["plans of both buildings", "midpoint definition and ancient surface level"],
    priority="low", scorability="area-level until a pair is proposed",
    evidence=[("Lefkovits reads הבתין 'the two buildings'.", "via shared/readings.json e17")],
    inference=("Kept so that a building pair cannot be scored under the cave branch.", "low"), sources=["Lefkovits 2000 pp. 162–164"])
rec(id="P17-C", entry="17", branch="Milik 'two tamarisks'",
    reading_assumed="הבינין 'the two tamarisks'", reading_editions=["Milik 1962 D5 p. 263"], reading_status="disputed",
    place_id="nuweimeh", feature_type="two trees (not preserved)", feature_detail="Trees 'could easily have disappeared' (Milik).",
    orientation="none", measures=[{"cubits": 3, "edition": "Milik 1962", "type": "digging depth"}],
    location="Valley of Achor; not locatable.", confirm="Not scorable from excavation (landmark perishable).",
    miss="Not scorable.", inconclusive="Always.", report_extra=[], priority="low", scorability="not scorable",
    evidence=[("Milik: the trees 'could easily have disappeared'.", "Milik 1962 D5 p. 263 via shared/readings.json")],
    inference=("Recorded only to make the branch explicit.", "high"), sources=["Milik DJD III p. 263"])

# ---------------------------------------------------------------- entry 18
rec(id="P18-A", entry="18", branch="Puech 'earth pit' at the edge of ʿAṣla",
    reading_assumed="בשית האדמא 'earth pit' (dug in earth, not rock); שבשולי 'at the edge'; העצלא one word = ʿAṣla",
    reading_editions=["Puech 2015 p. 52 and n. 206"], reading_status="disputed (Lefkovits reads 'the wood … in it', no place)",
    place_id="asla", feature_type="pit dug in soft ground (earth/marl), not in rock",
    feature_detail="Puech places ʿAṣla between ʿAyn Nabi Musa and the cliffs north of Qumran.", orientation="none", measures=[],
    location="Wadi el-ʿAṣla/Gofet el-ʿAṣla area NW Dead Sea (gazetteer area ~3 km), at the edge of the named feature.",
    confirm="L2: a pit cut into earth/marl, dated before 135 CE, at the margin of the ʿAṣla watercourse. L4: silver.",
    miss="Feature-level only.", inconclusive="Undated pits; which ʿAṣla is meant (Q23) unresolved.",
    report_extra=["pit cut profile and fill sequence with dating", "matrix (marl/earth vs rock)", "position relative to the wadi edge or spring outlet"],
    priority="low", scorability="area-level",
    evidence=[("Puech: 'earth pit', dug in ground not rock; red marl is common in the area.", "Puech 2015 p. 52 and n. 206 via shared/readings.json"),
              ("No pit reported.", "via shared/phase5_archaeology_index.csv")],
    inference=("Weak area prediction.", "low"), sources=["SWP III p. 200", "Milik DJD III D6", "ʿAtiqot 41 (Yitah et al.) pp. 180–185"])
rec(id="P18-B", entry="18", branch="Milik 'Red Pit' at a spring outlet (ʿEin Nebi Musa)",
    reading_assumed="'Red Pit' in red marl; שולי = outlet of a spring", reading_editions=["Milik 1962 C15, D6 p. 263"], reading_status="disputed",
    place_id="asla", feature_type="pit in red marl at a spring outlet", feature_detail="Milik ties the entry to the outlet of a spring (ʿEin Nebi Musa).",
    orientation="none", measures=[], location="At a spring outlet in the ʿAṣla/Mukellik–ʿAṣla–Daber torrent system.",
    confirm="L2: a pre-135 CE pit in red marl at a spring outlet in that system.", miss="Feature-level only.", inconclusive="As P18-A.",
    report_extra=["spring outlet position", "pit matrix and date"], priority="low", scorability="area-level",
    evidence=[("Milik: Wadi el-ʿAṣla, part of the Mukellik–ʿAṣla–Daber torrent; outlet of a spring.", "Milik 1962 D6 p. 263 via shared/readings.json")],
    inference=("Branch kept separate from P18-A.", "low"), sources=["Milik DJD III D6"])

# ---------------------------------------------------------------- entry 20
rec(id="P20-A", entry="20", branch="יגר = cairn (Milik, Puech); Sekakah valley = Wadi Qumran",
    reading_assumed="ביגר 'in the cairn' of the valley of Sekakah; dig 1 cubit", reading_editions=["Milik 1962 C77", "Puech 2015 pp. 53–54", "Høgenhaven 2020 p. 66 n. 39"],
    reading_status="letters secure; meaning disputed (cairn vs dam)", place_id="wadi_qumran",
    feature_type="stone cairn (possibly over a burial) in the valley", feature_detail="A heap of stones in the lower Wadi Qumran; Puech rejects 'dam' because a flood could carry the deposit away.",
    orientation="none", measures=[{"cubits": 1, "edition": "all", "type": "digging depth"}],
    location="Wadi Qumran below Kh. Qumran (gazetteer ~500 m).",
    confirm="L2: a cairn shown by sealed finds or the burial it covers to exist before 135 CE in the valley floor/terraces below Kh. Qumran; L3: a period cavity 0.45–0.53 m (1 c.) into the cairn or beneath its base.",
    miss="Feature-level only (many cairns; a single empty cairn does not refute the branch).",
    inconclusive="Undated cairns; modern cairns (field clearance) not distinguished.",
    report_extra=["cairn dating evidence (finds within/under it, burial beneath)", "depth of any cavity from cairn top and from cairn base", "distinction from modern cairns"],
    priority="low", scorability="area-level",
    evidence=[("Stone-capped graves are reported at Qumran.", "via repo phase5_summary §4 (SWP III p. 210; Milik D8)"),
              ("Puech: cairn; rejects 'dam'.", "Puech 2015 pp. 53–54 via shared/readings.json")],
    inference=("Nahal Sekakah is not an independent name witness (modern name derived from the identification).", "medium"),
    sources=["Eshel CSS pp. 94–95", "SWP III p. 210", "ʿAtiqot 41 (Baruch et al.) pp. 197–198", "Israel Guide 13 p. 176 (via repo site_identification_review)"])
rec(id="P20-B", entry="20", branch="יגר = dam (Eshel, Lurie) at the head of the Qumran aqueduct",
    reading_assumed="'dam' where the Qumran aqueduct starts; dig 1 cubit", reading_editions=["Eshel 2002 CSS pp. 101–102", "Lurie 1964"],
    reading_status="disputed", place_id="kh_qumran",
    feature_type="diversion dam at the aqueduct intake", feature_detail="The dam is reconstructed (lost); Ilan–Amit's main-basin dam vs Reeder–Jol's upstream wall are not yet shown to be one feature.",
    orientation="none", measures=[{"cubits": 1, "edition": "all", "type": "digging depth"}],
    location="Intake of the Qumran aqueduct in Wadi Qumran (west of the settlement); gazetteer anchor is the settlement (~100 m), not the intake.",
    confirm="L2: remains of a dam at the intake dated before 70 CE (Stacey: main aqueduct after 31 BCE); L3: a period cavity 0.45–0.53 m into the dam body or foundation.",
    miss="Dam remains exposed and shown to be later than 135 CE only, or the dam footprint excavated to its base without a period cavity.",
    inconclusive="Dam footprint not located; phase undetermined.",
    report_extra=["dam footprint with control points tying it to Ilan–Amit 1989 Fig. 1 and Reeder–Jol 2006 Fig. 4", "construction phase relative to the aqueduct channel", "depth of any cavity from the dam crest"],
    priority="medium", scorability="feature-level",
    evidence=[("Eshel: the dam where the Qumran aqueduct starts.", "Eshel CSS pp. 101–102 via shared/readings.json"),
              ("Older dam inferred; later survey reports an upstream wall; identity unverified.", "via shared/feature_constraints.csv (Ilan & Amit 1989 p. 284 Fig. 1 pt 4; Reeder & Jol 2006 p. 231 Fig. 4)")],
    inference=("Overlaps physically with P21; scored separately because the landmark word differs.", "medium"),
    sources=["Eshel CSS pp. 94–95, 101–102", "Ilan & Amit 1989 pp. 283–285", "Reeder & Jol 2006", "Stacey 2007 DSD 14 pp. 222–243"])

# ---------------------------------------------------------------- entry 21
c21 = dict(entry="21", place_id="kh_qumran",
    reading_assumed="ברוש אמת המים … סככא מן הצפון תחת [האבן] הגדולא חפור אמות [שלו]ש (Puech: link ש[במערב] 'west of'; 'great [stone]' restored after Milik; 3 cubits restored)",
    reading_editions=["Puech 2006 p. 188; 2015 pp. 54–55", "Milik 1962 D9 p. 263"],
    reading_status="mixed: 'head of the conduit' secure; link word lost; 'stone' restored; depth restored (Lefkovits: 3, 5 or 6)",
    feature_type="large stone on the north side of the head of the water conduit, deposit under it",
    orientation="'on the north side' (cache north of the head) OR 'from the north' (flow direction) — test separately; the stone must be on the north side under the first sense",
    measures=[{"cubits": 3, "edition": "Puech 2006 (restored)", "type": "digging depth under the stone"},
              {"cubits": 5, "edition": "Lefkovits 2000 option", "type": "digging depth"},
              {"cubits": 6, "edition": "Lefkovits 2000 option", "type": "digging depth"}],
    report_extra=["which 'head' is meant: intake, branch junction, tunnel mouth, earlier construction-stage head; with plan reference (Ilan–Amit 1989 Fig. 1 point numbers; Reeder–Jol 2006 Fig. 4)",
                  "large stones within ~10 m of that head: dimensions, position (azimuth from the channel start), whether in situ bedrock, built-in, or later rock-fall/flood-borne",
                  "stratigraphic relation of the stone to the channel construction and to dated deposits",
                  "depth below the stone's base excavated and sediment dates to ≥3.2 m (6 c. upper bound)",
                  "channel construction phase and dating evidence (Stacey's post-31 BCE phasing)"],
    priority="high", scorability="feature-level",
    sources=["Eshel CSS pp. 94–95", "Puech 2006 pp. 187–189", "Lefkovits 2000 pp. 185–189", "Ilan & Amit 1989 pp. 283–285 Fig. 1", "Reeder & Jol 2006 Fig. 4 p. 229, p. 231", "Stacey 2007 DSD 14 pp. 222–243", "Magen & Peleg 2018 pp. 78–79"])
rec(id="P21-A", branch="head = visible channel start at Ilan–Amit point 3 (intake beside reconstructed dam)",
    feature_detail="Best functional match for the head of the whole aqueduct; at a small ravine on the northern bank (repo candidate A).",
    location="Intake sector of the Qumran aqueduct in Wadi Qumran; the gazetteer anchor (settlement, ~100 m) does not locate it — use Ilan–Amit 1989 Fig. 1 point 3.",
    confirm="L2: at point 3, a large stone (boulder or block) lying on the north side of the channel start, shown to be in place before or during the aqueduct's use (before 70 CE); L3: a period cut/cavity under it at 1.34–1.58 m (3 c.) [2.23–2.63 m for 5 c.; 2.67–3.15 m for 6 c.].",
    miss="Every large stone on the north side of the point-3 head is shown to have arrived after 135 CE, or excavation beneath each to ≥3.2 m reaches undisturbed pre-Roman sediment/bedrock with no period cut. (Under the 'flow from the north' sense the miss criterion does not apply; record as inconclusive.)",
    inconclusive="Stone position relative to the head unrecorded; head identity unresolved; excavation shallower than the edition's depth.",
    evidence=[("Ilan–Amit 1989 put the visible intake beside a reconstructed dam; the original Hebrew plan was reviewed; cross-survey identity unresolved.", "via shared/feature_constraints.csv and entries.json"),
              ("Repo candidate register ranks Ilan point 3 first (investigative priority, not probability).", "via repo entry21_candidates.json")],
    inference=("Most specific feature-level prediction in the registry; still conditional on Sekakah = Qumran and on the restored noun.", "medium (site); low (feature)"), **c21)
rec(id="P21-B", branch="'great stone' = Reeder's ~3 m boulder beside the upstream collection works",
    feature_detail="Reeder describes an approximately 3 m-high boulder incorporated into the works beside the upstream channel (repo candidate B); its correspondence with point 3 is unproved.",
    location="Upstream collection works (Reeder–Jol 2006 Fig. 4); relation to Ilan point 3 to be fixed by a survey with shared control points.",
    confirm="L2: the boulder is shown to lie on the north side of the conduit head and to predate the aqueduct's use; L3: period cut under/against its base at 1.34–1.58 m (or the 5/6-cubit windows).",
    miss="The boulder is shown to sit south of the head (under the 'north side' sense), or excavation under it to ≥3.2 m finds undisturbed pre-Roman deposits/bedrock.",
    inconclusive="As P21-A.",
    evidence=[("Reeder–Jol 2006 p. 231: c. 3 m-high boulder incorporated into the upstream works.", "via repo entry21_candidates.json")],
    inference=("Danger of circularity: the noun is restored; a boulder cannot validate its own restoration. Score only the deposit level as evidence.", "low"), **c21)
rec(id="P21-C", branch="head = branch junction / short western tunnel (subsection head)",
    feature_detail="Possible beginning of a collecting branch (Ilan–Amit points 7–10; probably Reeder Tunnel 2).",
    location="Ilan–Amit 1989 points 7–10.",
    confirm="L2: junction shown to be a head of a branch in use before 70 CE with a large stone on its north side; L3 as P21-A.",
    miss="As P21-A for this junction.", inconclusive="Flow direction/branch function unresolved.",
    evidence=[("Repo candidate C: branch function and flow direction differ among published interpretations.", "via repo entry21_candidates.json (Ilan–Amit 1989 p. 284; Magen–Peleg 2018 p. 78)")],
    inference=("Needs a 'subsection head' reading.", "low"), **c21)
rec(id="P21-D", branch="head = western mouth of the long eastern tunnel",
    feature_detail="Downstream of the intake (repo candidate D); captions disagree whether the photographed mouth is entrance or exit.",
    location="Ilan–Amit point 11 / Reeder Tunnel 1 (probable correspondences).",
    confirm="L2: the mouth shown to be the head of a construction stage before 70 CE with a large stone on its north side; L3 as P21-A.",
    miss="As P21-A for this mouth.", inconclusive="As P21-A.",
    evidence=[("Reeder Fig. 2 and Magen Fig. 87 match the same long-tunnel mouth.", "via repo entry21_candidates.json")],
    inference=("Lowest-ranked head; downstream position conflicts with 'head of the whole conduit'.", "low"), **c21)
rec(id="P21-E", branch="head = start of an earlier construction stage near Ilan–Amit point 16 (Stacey phasing)",
    feature_detail="Under Stacey 2007, the earlier channel began where the aqueduct leaves the cliff (near point 16); dam and cliff tunnel are a later stage.",
    location="Near Ilan–Amit 1989 Fig. 1 point 16.",
    confirm="L2: stratigraphic evidence that the channel began near point 16 in an earlier phase, plus a large stone on its north side; L3 as P21-A.",
    miss="Phasing refuted by stratigraphy (single build), which closes this branch; or as P21-A for the stone.",
    inconclusive="Phasing untested.",
    evidence=[("Stacey 2007 pp. 222–228 nn. 28–30: phasing hypothesis; 2002 figure numbering unchecked.", "via shared/feature_constraints.csv")],
    inference=("A phasing test can close this branch without any treasure search.", "medium"), **c21)

# ---------------------------------------------------------------- entry 22
c22 = dict(entry="22", place_id="kh_qumran",
    reading_assumed="בסדק שבסככא מזרח אשוח שלומו: 'in the fissure in Sekakah, east of the Reservoir of Solomon'; vessels of offering and 'their record beside them'",
    reading_editions=["Puech 2006 p. 188; 2015 pp. 55–56", "Milik 1960 p. 147; 1962 D10–D11"],
    reading_status="letters agreed; reservoir name unattested at Qumran; Milik's segmentation detaches ובתכן אצלם into a new item",
    feature_type="natural fissure/crack east of a named large reservoir",
    orientation="fissure lies east of the reservoir", measures=[],
    report_extra=["which reservoir/cistern is the reference (locus number) and its construction phase", "fissures/cracks within ~30 m east of it: position, width, depth, fill and dating",
                  "any inscribed material (ostracon, scroll, tablet) found with vessels — the entry predicts a written record beside the vessels"],
    priority="medium", scorability="feature-level",
    sources=["Cohen & Porat, HA-ESI 132 (2020)", "Milik 1960 p. 147", "SWP III p. 210", "Puech 2006 pp. 187–189"])
rec(id="P22-A", branch="reservoir = the large cistern SE of the site (Milik 1960)",
    feature_detail="Milik 1960 p. 147: 'undoubtedly' the cistern south-east of the site excavated by de Vaux.",
    location="East of the SE cistern of Kh. Qumran (settlement anchor ~100 m).",
    confirm="L2: a fissure east of the SE cistern, open in the 1st c. CE; L4: vessels with an inscribed record beside them.",
    miss="Ground east of the SE cistern exposed to bedrock across ~30 m with no fissure open in the period.",
    inconclusive="Fissures present but undated; natural cracks from the 31 BCE earthquake not distinguished.",
    evidence=[("Milik 1960 p. 147: the SE cistern.", "via shared/readings.json e22"), ("Natural cracks in the marl with 1st-century activity are documented.", "via repo phase5_summary §4 (Cohen & Porat HA-ESI 132)")],
    inference=("Reservoir name is unattested; the branch rests on Milik's choice.", "low"), **c22)
rec(id="P22-B", branch="fissure = the long tunnel's internal openings east of basin 2 (repo test)",
    feature_detail="The repo tests the long tunnel's two openings as entry-22 candidates east of basin 2, conditional on the unestablished reservoir name.",
    location="Long tunnel of the aqueduct, east of basin 2 (Ilan–Amit plan).",
    confirm="L2: a fissure/opening east of a basin that is independently shown to be called Solomon's (or the only great reservoir of the sector); L4 as P22-A.",
    miss="Not definable until the reference basin is fixed; record inconclusive.", inconclusive="Default.",
    evidence=[("Repo feature investigation: long tunnel's two openings tested as entry-22 candidates east of basin 2.", "repo feature_investigation.md (Entry 21 feature comparison, 28 Sep 2026)")],
    inference=("Dependent on P21 geometry.", "low"), **c22)

# ---------------------------------------------------------------- entry 23
rec(id="P23-A", entry="23", branch="Solomon's trench = Qumran main distribution channel; 60 cubits to the great heap/boulder",
    reading_assumed="מעל החריץ של שלומו עד הרגם/הרגב הגדול אמות ששין חפור אמות שלוש", reading_editions=["Milik 1960 p. 147", "Puech 2006 pp. 188–189"],
    reading_status="disputed (Solomon vs Shallum; heap/mound vs boulder)", place_id="kh_qumran",
    feature_type="large heap of stones or boulder 60 cubits from a named trench/channel",
    feature_detail="From the trench of Solomon to the great heap (or boulder), 60 cubits; dig 3 cubits.",
    orientation="not stated", measures=[{"cubits": 60, "edition": "all", "type": "horizontal distance trench→landmark"}, {"cubits": 3, "edition": "all", "type": "digging depth"}],
    location="Kh. Qumran (settlement anchor ~100 m); origin point on the channel not specified.",
    confirm="L2: a heap/boulder of the period whose distance from the main channel (nearest point or a named outlet) is 26.7–31.5 m (60 c.); L3: period cut at 1.34–1.58 m at the landmark.",
    miss="Feature-level only.", inconclusive="Origin on the channel undefined; landmark undated.",
    report_extra=["distance and azimuth from defined channel points to the landmark", "landmark type (cairn/burial mound/boulder) and date"],
    priority="low", scorability="feature-level only once origin fixed",
    evidence=[("Milik 1960: 'Canal of Solomon', the site's main distribution channel.", "via shared/readings.json e23"), ("Puech 2015 p. 58 prefers Shallum and doubts Solomon.", "via shared/readings.json e23")],
    inference=("Geometry not performed in the repo; no origin; low.", "low"), sources=["Puech 2006 pp. 187–189", "Milik 1960 p. 147"])
rec(id="P23-B", entry="23", branch="Shallum's trench (Puech 2015) — no Qumran link required",
    reading_assumed="של שלום 'of Shallum'", reading_editions=["Puech 2006 p. 189; 2015 p. 58"], reading_status="disputed",
    place_id="kh_qumran", feature_type="trench named for Shallum + great heap 60 cubits away", feature_detail="Link to entry 22's reservoir falls away.",
    orientation="none", measures=[{"cubits": 60, "edition": "all", "type": "distance"}, {"cubits": 3, "edition": "all", "type": "depth"}],
    location="Unlocated beyond the Sekakah sequence.", confirm="Not scorable until a Shallum toponym/feature is proposed.",
    miss="Not scorable.", inconclusive="Default.", report_extra=[], priority="low", scorability="not scorable",
    evidence=[("Puech 2015 p. 58: Shallum.", "via shared/readings.json")], inference=("Branch recorded for completeness.", "high"),
    sources=["Puech 2015 p. 58"])

# ---------------------------------------------------------------- entry 24
rec(id="P24-A", entry="24", branch="Naḥal ha-Kippa = Wadi Kuteif; tomb on the way from Jericho to Sekakah",
    reading_assumed="בקבר שבנחל הכפא בביאה מירחו לסככא חפור אמות שבע", reading_editions=["Milik 1962 D12 p. 264", "Puech 2015 p. 59"],
    reading_status="letters agreed; Kippa = rock/cavern disputed; Allegro removes Jericho", place_id="kuteif",
    feature_type="tomb in a wadi on the Jericho–Sekakah approach", feature_detail="Milik: a stepped underground chamber in Wadi Kuteif, 'probablement un tombeau'.",
    orientation="none", measures=[{"cubits": 7, "edition": "all", "type": "digging depth"}],
    location="Wadi Kuteif (gazetteer area ~3 km).",
    confirm="L2: a tomb in Wadi Kuteif dated before 135 CE (the recorded chamber, if dated, or another); L3: a period cut 3.1–3.7 m (7 c.) below the tomb floor/entrance level.",
    miss="Feature-level: the recorded chamber dated only after 135 CE or shown not to be a tomb.",
    inconclusive="Chamber undated.", report_extra=["date and function of the stepped chamber", "depth reached below its floor"],
    priority="low", scorability="feature-level for the recorded chamber",
    evidence=[("The recorded rock-cut chamber is undated and does not identify the required tomb.", "via shared/entries.json (SWP III p. 220; Milik DJD D12)")],
    inference=("Route-based placement.", "low"), sources=["SWP III p. 220", "Milik DJD III D12"])

# ---------------------------------------------------------------- entry 25
c25 = dict(entry="25", place_id="kh_qumran",
    reading_assumed="במערת העמוד של שני הפתחין הצופא מזרח בפתח הצפוני חפור אמות שלוש שם קלל בו ספר אחד",
    reading_editions=["Milik 1960 p. 140 item 27, p. 147", "Puech 2015 pp. 59–60"],
    reading_status="partly restored; eastward aspect attaches to the cave (Milik), stricter model = both mouths face east",
    feature_type="cave with a pillar and two openings, facing east; deposit at the northern opening",
    orientation="cave aspect east; 'northern opening' = the northern member of the pair (not necessarily north-facing)",
    measures=[{"cubits": 3, "edition": "all", "type": "digging depth at the northern opening"}],
    report_extra=["surveyed bearings of both openings", "whether the openings communicate internally", "dated threshold/surface at the northern opening",
                  "depth excavated at the northern opening to ≥1.6 m", "any jar with a scroll (jar type, scroll material) — the entry predicts one jar containing one book"],
    priority="medium", scorability="feature-level",
    sources=["Milik 1960 p. 140", "Puech 2015 pp. 59–60", "Bar-Adon 1989 pp. [15]–17 (via repo R02)"])
rec(id="P25-A", branch="Twin Cave near Cave 11Q (Bar-Adon)", feature_detail="Bar-Adon reports a pillar and two openings, both published as facing east.",
    location="Twin Cave near 11Q (not in the gazetteer; settlement anchor only).",
    confirm="L2: openings' surveyed bearings east, pillar confirmed, use in 1st c. BCE–1st c. CE; L3: period cut at the northern opening 1.34–1.58 m below the ancient threshold; L4: jar with scroll fragments.",
    miss="Northern opening excavated to bedrock or to ≥1.6 m below the ancient threshold through undisturbed pre-Roman fill.",
    inconclusive="Bearings unsurveyed; threshold surface undated.",
    evidence=[("Bar-Adon pp. [15]–17 supports Twin Cave's pillar and two openings, both facing east; bearings/spacing unresolved.", "via repo research_OPEN_QUESTIONS.md R02")],
    inference=("Best documented match to the textual description among the repo's cave records.", "low-medium"), **c25)
rec(id="P25-B", branch="Abu Saraj IV/17 (measured two-mouth/pillar plan)", feature_detail="IV/17 supplies a measured two-mouth/pillar plan without a dated first-century threshold.",
    location="Abu Saraj IV/17 (not in the gazetteer).",
    confirm="As P25-A.", miss="As P25-A.", inconclusive="As P25-A.",
    evidence=[("IV/17 supplies a measured two-mouth/pillar plan without a dated first-century threshold; Dadon's L-656 file pending.", "via repo R02")],
    inference=("Rival to P25-A.", "low"), **c25)
rec(id="P25-C", branch="Abu Saraj IV/11 (internal pillar)", feature_detail="IV/11's internal pillar and upper-fill coins do not establish the exterior pair or phase.",
    location="Abu Saraj IV/11.", confirm="As P25-A (requires an exterior pair of openings).", miss="Shown to have one opening only.", inconclusive="As P25-A.",
    evidence=[("IV/11: internal pillar; upper-fill coins; exterior pair not established.", "via repo R02")],
    inference=("Weakest of the three.", "low"), **c25)

# ---------------------------------------------------------------- entry 28
rec(id="P28-A", entry="28", branch="cairn at a lower-Jordan ford near Jericho",
    reading_assumed="ביגר שבמגזת הכוהן הגדול חפור … תשע", reading_editions=["Milik 1962 D16 p. 264", "Puech 2015 pp. 62–63"],
    reading_status="'ford' (Milik, Puech) vs 'bridge' (Allegro, Lefkovits)", place_id="jordan_ford",
    feature_type="cairn at a river ford", feature_detail="A heap of stones at 'the ford of the High Priest'.", orientation="none",
    measures=[{"cubits": 9, "edition": "Puech/Milik", "type": "digging depth"}], location="Lower Jordan near Jericho (area ~10 km; river migration).",
    confirm="L2: a cairn of the period at a documented ancient ford; L3: period cut at 4.0–4.7 m.", miss="Not definable.", inconclusive="Default.",
    report_extra=["ancient channel position", "cairn date"], priority="low", scorability="not scorable at present",
    evidence=[("No archaeology for any ford.", "via repo phase5_summary §5")], inference=("River migration makes the landmark unlikely to survive.", "medium"),
    sources=["SWP III p. 170"])

# ---------------------------------------------------------------- entry 29
c29 = dict(entry="29",
    reading_assumed="באמא של קי◦ … האשיח הצפוני הגדול בארבע רוחות … משח אמות עסרין וארבע",
    reading_status="place word broken (Puech qyb[wṣ] 'collection'; Milik qy[ṣyṣ]; Eshel Qi[dron]/Cy[pros]); 'of Jericho' restored by Puech",
    feature_type="great northern reservoir measured 24 cubits on its four sides, with a conduit",
    orientation="'northern' reservoir: the northern one of a set",
    measures=[{"cubits": 24, "edition": "all", "type": "side length OR offset from each side (unresolved)"}],
    report_extra=["internal and external side lengths of the reservoir at the ancient floor and rim, per phase", "inlet/conduit position and invert", "phase of each wall face", "which reservoir in the set is northernmost"],
    priority="medium", scorability="feature-level")
rec(id="P29-A", branch="Hasmonean–Herodian palace pools, Jericho (Puech's 'of Jericho' restoration)", place_id="jericho_palaces",
    reading_editions=["Puech 2006 (restoration)"], feature_detail="Northern great reservoir among the palace pools (repo assessment currently on A(C)94 with an early north-wall pipe).",
    location="Tulul Abu el-ʿAlayiq palaces (gazetteer ~300 m).",
    confirm="L2: a pool that is the northern one of its complex, with sides 10.7–12.6 m (24 c.) at a defined phase, or an independently justified offset model; L3: period cut at the predicted offset.",
    miss="All northern great pools of the complex have phase-specific sides outside 10.7–12.6 m AND no offset model is textually justified.",
    inconclusive="Wall-face/aperture datum undefined (current repo status for A(C)94).",
    evidence=[("A(C)94 early-pipe test: drawn-terminus model misses 24/27 cubits; whole-pipe model gives conditional fits; 'not identifiable from available evidence'.", "via repo research_ACTIVE_TEST.md")],
    inference=("The repo's most-tested branch; still no defined datum.", "low"), sources=["Netzer 2001 (via repo)", "Eshel CSS pp. 99–100"], **c29)
rec(id="P29-B", branch="Hyrcania northern pools (Eshel: Qi[dron] = southern aqueduct)", place_id="hyrcania",
    reading_editions=["Eshel 2002 CSS pp. 103–105"], feature_detail="One of Hyrcania's 'N pools'.",
    location="Hyrcania (Kh. el-Mird) and its aqueducts (gazetteer ~200 m).",
    confirm="L2: an offset interpretation (e.g., 24 c. northward from a defined origin) independently justified, plus period use in the 1st c. CE; L3: period cut at the predicted point.",
    miss="Side-length model already fails (reported sides 15–19 m vs 10.7–12.6 m); a demonstrated abandonment of the fortress before the scroll's period would weaken the branch.",
    inconclusive="Offset origin undefined.",
    evidence=[("Northern pool's reported sides 15–19 m fail a conditional 24-cubit side test at 0.445–0.525 m/cubit; offset interpretation open.", "via repo site_identification_review.md (cave plan follow-up 30 Sep)"),
              ("Patrich: fortress abandoned after Herod's death.", "via repo site_identification_review.md (Patrich 2002 p. 336)")],
    inference=("Side-length test is already a recorded MISS for that model; only an offset model remains.", "medium"), sources=["Eshel CSS pp. 92, 95, 97, 103–105", "Garbrecht & Peleg BA 57 (1994) pp. 168–169"], **c29)
rec(id="P29-C", branch="ʿAin Duk / Naʿaran springs or Tell es-Sultan (unspecified pools)", place_id="ain_duk",
    reading_editions=["repo Phase 3 candidates"], feature_detail="Possible only; no specific reservoir.",
    location="ʿAin Duk springs (~300 m); Tell es-Sultan alternative (see places.json tell_es_sultan).",
    confirm="L2: a period northern great reservoir with 24-cubit sides.", miss="Not definable.", inconclusive="Default.",
    evidence=[("Kept as possible only.", "via shared/entries.json")], inference=("Placeholder.", "low"), sources=["Phase 3 site index"], **c29)

# ---------------------------------------------------------------- entry 30
rec(id="P30-A", entry="30", branch="Puech: cave next to the frigidarium ('cool room') of the House of Haqqoz, Jericho oasis",
    reading_assumed="במערא שאצל המקרא של בית הקץ חפר אמות שש (Puech: המקר[ה] 'the cool room'; בית הקצ = house of Haqqoz)", reading_editions=["Puech 2002 CSS pp. 71–72", "Puech 2015 pp. 62, 65–66"],
    reading_status="restored (mem assured, rest probable); Milik reads 'in its vicinity'", place_id="jericho_area",
    feature_type="cave adjacent to the cold room of a bath-house in a priestly-family estate",
    feature_detail="A bath with a frigidarium belonging to a house/estate of the Haqqoz family, with a cave next to it.",
    orientation="none", measures=[{"cubits": 6, "edition": "all", "type": "digging depth"}], location="Jericho oasis (area ~3 km).",
    confirm="L2: a 1st c. BCE–1st c. CE bath with an identifiable frigidarium and an adjacent cave in the oasis (owner identification optional but scored separately); L3: period cut 2.7–3.2 m in the cave.",
    miss="Feature-level only.", inconclusive="Bath without a cave, or cave without bath.",
    report_extra=["room functions of the bath suite (frigidarium identification)", "cave relation (adjacent wall/door) and date", "any family-name inscriptions"],
    priority="low", scorability="area-level", evidence=[("Baths, pools and caves of the period are reported in the oasis.", "via shared/phase5_archaeology_index.csv (Eshel CSS pp. 99–100; Puech 2015 pp. 36, 101)")],
    inference=("Conjunction cave+frigidarium is specific; the estate is not.", "low"), sources=["Eshel CSS pp. 99–100", "Puech 2015 pp. 36, 66, 101"])
rec(id="P30-B", entry="30", branch="Milik: Tell el-Qos (house of the priestly family Haqqoṣ)",
    reading_assumed="בקרבו 'in its vicinity'; בית הקצ at Tell el-Qos", reading_editions=["Milik 1962 D18 p. 265"], reading_status="disputed",
    place_id="tell_el_qos", feature_type="cave near a house at Tell el-Qos", feature_detail="Phase 5 lowered Tell el-Qos to weak (a heap of stones).",
    orientation="none", measures=[{"cubits": 6, "edition": "all", "type": "digging depth"}], location="Tell el-Qos (gazetteer ~200 m).",
    confirm="L2: a period house with an adjacent cave at Tell el-Qos.", miss="Excavation shows no pre-Byzantine occupation at Tell el-Qos.",
    inconclusive="Surface survey only.", report_extra=["earliest occupation phase"], priority="low", scorability="site-level",
    evidence=[("SWP p. 222: a heap of stones, 'not a Tell in the strict meaning'; PADIS reports Byzantine remains.", "via repo phase5_summary §3 and shared/readings.json")],
    inference=("Weak.", "low"), sources=["SWP III p. 222", "Milik DJD III D18"])

# ---------------------------------------------------------------- entry 31
c31 = dict(entry="31", measures=[{"cubits": 7, "edition": "all", "type": "digging depth (vertical)"}],
    report_extra=["room/installation functions on the summit with evidence (drying installation vs guard room)", "phase plan (Hasmonean / Herodian / later) for each wall corner",
                  "absolute elevation of the ancient floor at the relevant corner", "depth reached below that floor (≥3.7 m)", "which building is 'eastern' if several posts exist"],
    priority="high", scorability="feature-level",
    sources=["Eshel CSS pp. 92, 100–101", "Milik DJD III D19", "Puech 2006 p. 192; 2015 p. 67", "Lefkovits 2000 pp. 232–235", "Amit 1989 pp. 223–228 (Fig. 2 p. 224)", "Garbrecht & Peleg BA 57 (1994) pp. 164–165", "Netzer 2006 p. 207 n. 25"])
rec(id="P31-A", branch="drying place (Puech hmšṭḥ); 'eastern' modifies the corner", place_id="doq",
    reading_assumed="בדוק תחת פנת hmšṭḥ ('drying place') המזרחית חפור אמות שבע", reading_editions=["Puech 2006 p. 192; 2015 p. 67"], reading_status="plates lean to hmšṭḥ; not decisive",
    feature_type="eastern corner of a spreading/drying installation at Doq", feature_detail="An installation with evidence of drying/spreading function (e.g., plastered flat surface), at the Doq fortress (Puech 2015 places Doq at the fortress).",
    orientation="the corner that is eastern", location="Jebel Qarantal summit/NE spur (gazetteer ~300 m).",
    confirm="L2: a dated (pre-135 CE) installation with demonstrated drying function and a measurable eastern corner; L3: period cut 3.1–3.7 m below the floor at that corner.",
    miss="Complete publication of the summit/spur installations with functions shows no drying installation of the period (weaker if later construction erased earlier remains).",
    inconclusive="Installations undated or function unproven.",
    evidence=[("Plates lean to Puech's hmšṭḥ (two letters after ש, final ח); not decisive.", "via shared/feature_constraints.csv (plate_check)"), ("Puech's drying floor has no archaeological counterpart reported.", "via repo phase5_summary §4")],
    inference=("Text-preferred branch has no known feature; a new observation is required.", "medium"), **c31)
rec(id="P31-B", branch="guard post (Milik, Lefkovits); eastern corner of the post", place_id="doq",
    reading_assumed="תחת פנת המשמרה המזרחית", reading_editions=["Milik 1962 D19", "Lefkovits 2000 pp. 232–235", "Eshel 2002 p. 104"], reading_status="disputed",
    feature_type="eastern corner of the guard post/fortress", feature_detail="Hasmonean summit fortress (wadi diversion, 500 m channel, nine cisterns).",
    orientation="eastern corner", location="Jebel Qarantal summit (gazetteer ~300 m).",
    confirm="L2: a dated plan identifying the guard building and its eastern corner in use before 135 CE (Herodian rebuilding not shown); L3: period cut 3.1–3.7 m below the floor at that corner.",
    miss="The building's eastern corner excavated to ≥3.7 m below the ancient floor (or to bedrock) without a period cut.",
    inconclusive="Fortress plan unpublished (1982 finds unpublished per Netzer 2006).",
    evidence=[("A Hasmonean fortress occupied the summit; Garbrecht & Peleg: apparently not rebuilt by Herod, so 1st-century use is not shown.", "via shared/entries.json"), ("Netzer 2006 p. 207 n. 25: the 1982 Doq finds unpublished.", "via repo OPEN_QUESTIONS R10")],
    inference=("Archaeology favours this reading but must not choose it (repo rule).", "medium"), **c31)
rec(id="P31-C", branch="guard post; 'eastern' modifies the post (a corner of the eastern post)", place_id="doq",
    reading_assumed="פנת [ה]משמרה המזרחית = corner of the eastern guard post", reading_editions=["Lefkovits 2000 pp. 234–235"], reading_status="disputed",
    feature_type="a corner of the easternmost of several guard posts", feature_detail="Requires evidence for distinct posts.",
    orientation="corner not fixed", location="Doq fortress area.",
    confirm="L2: ≥2 posts documented, the eastern one identified and dated; L3: period cut at 3.1–3.7 m at one of its corners.",
    miss="Only one post exists (closes branch).", inconclusive="Default.",
    evidence=[("Lefkovits discusses the grammatical attachment.", "Lefkovits 2000 pp. 234–235 via repo dok_achor_feature_tests.md")],
    inference=("Four corners → weak spot prediction.", "low"), **c31)
rec(id="P31-D", branch="Doq = the spring area (ʿAin Duk), Puech 2006 gloss", place_id="ain_duk",
    reading_assumed="as P31-A or P31-B, located at the spring", reading_editions=["Puech 2006 p. 192 (north-west of Jericho, the spring area)"], reading_status="disputed",
    feature_type="corner of a drying place/guard post at ʿAin Duk", feature_detail="Name survives at ʿAin Duk; it does not distinguish summit from spring.",
    orientation="eastern corner", location="ʿAin Duk / Naʿaran springs (gazetteer ~300 m).",
    confirm="As P31-A/B at the spring.", miss="Feature-level only.", inconclusive="Default.",
    evidence=[("The surviving name does not distinguish summit from spring (Q24).", "via shared/entries.json")], inference=("Kept separate.", "low"), **c31)

# ---------------------------------------------------------------- entry 32
c32 = dict(entry="32", place_id="choziba",
    reading_editions=["Milik 1962 D20 p. 265", "Puech 2006 p. 192; 2015 pp. 62, 67–68", "Eshel 2002 CSS pp. 105–106"],
    measures=[{"cubits": 3, "edition": "all", "type": "digging depth (toward/as far as the second landmark)"}],
    report_extra=["identity of the outlet (spring head / channel exit / junction) with plan reference (SWP III pp. 227–228; Meshel–Amit 1989 Fig. 1 points)", "phase of the outlet and of the second landmark (wall) and whether they functioned together",
                  "ancient ground level at the outlet mouth", "distance and direction from the outlet mouth to the row of stones/wall", "depth reached (≥1.6 m)"],
    priority="high", scorability="feature-level",
    sources=["Eshel CSS pp. 97–100, 105–106", "SWP III pp. 205–206, 227–228", "Milik DJD III D20", "Meshel & Amit 1989 pp. 230–242"])
rec(id="P32-A", branch="outlet = ʿAin Qelt spring/channel head; second landmark = retaining wall (Milik)",
    reading_assumed="על פי יציאת המים של הכוזבא חפור אמות שלוש עד הטור (טור = retaining wall)", reading_status="Koziba vs Buz disputed; טור meaning disputed",
    feature_type="water outlet at a spring/channel head with a retaining wall ('row of stones')", feature_detail="Spring/source interpretation.",
    orientation="from the outlet mouth toward the wall", location="ʿAin Qelt in Wadi Qelt (the gazetteer stretch ~500 m is at Choziba/St George's).",
    confirm="L2: a pre-70 CE outlet at the ʿAin Qelt head with a contemporary retaining wall adjacent; L3: period cut 1.34–1.58 m at the mouth on the wall side.",
    miss="The only walls at the head are shown to be later than 135 CE, or the mouth zone excavated to ≥1.6 m below the ancient surface without a period cut.",
    inconclusive="Wall undated.", evidence=[("SWP distinguishes the spring channel, the division at Jisr ed-Deir and a cliffside wall opposite Deir el-Kelt.", "via repo feature_investigation.md (SWP III pp. 227–228)")],
    inference=("Three rival outlets; each scored separately.", "medium"), **c32)
rec(id="P32-B", branch="outlet = Jisr ed-Deir distribution junction",
    reading_assumed="as P32-A; outlet = channel division/junction", reading_status="as P32-A",
    feature_type="channel outlet/junction with an adjacent retaining wall", feature_detail="Outlet or distribution-junction interpretation.",
    orientation="toward the wall", location="Jisr ed-Deir, Wadi Qelt near the monastery.",
    confirm="As P32-A at Jisr ed-Deir.", miss="As P32-A.", inconclusive="As P32-A.",
    evidence=[("PEF Sheet XVIII supports a west/southwest bridge sector near the monastery.", "via repo OPEN_QUESTIONS R03")], inference=("", "low"), **c32)
rec(id="P32-C", branch="outlet = lower culvert mouth at the wall opposite Deir el-Kelt",
    reading_assumed="as P32-A", reading_status="as P32-A",
    feature_type="culvert mouth in a cliffside retaining wall carrying channels", feature_detail="Provisional relative anchor; footprint and construction date unresolved; Milik 1960 p. 149 derives his wall proposal from SWP.",
    orientation="toward/along the wall", location="Cliffside wall opposite Deir el-Kelt (St George's).",
    confirm="L2: wall and culvert dated before 70 CE and shown to function together; L3 as P32-A.",
    miss="Wall construction shown to be Byzantine/early Arab only with no earlier channel bed (cf. Meshel–Amit: pipe aqueduct 7th–8th c. CE elsewhere).",
    inconclusive="Repairs vs earlier bed not distinguished.",
    evidence=[("Meshel–Amit 1989: point 25 has an earlier outlet bed and a later channel; pipe aqueduct assigned to the 7th–8th c. CE.", "via repo feature_investigation.md (Meshel–Amit 1989 Fig. 1 p. 230; Fig. 24 p. 241; p. 242)")],
    inference=("Correlation of Meshel–Amit point 25 with the SWP wall is unproved.", "low"), **c32)
rec(id="P32-D", branch="second landmark = mountain/parapet (Puech) or rock (Eshel): no wall required",
    reading_assumed="טור = mountain or parapet (Puech); הסור 'the rock' (Eshel)", reading_status="disputed",
    feature_type="water outlet at Koziba, deposit dug toward a mountain/rock", feature_detail="Direction toward the second landmark, endpoint/horizontal distance not fixed.",
    orientation="toward the mountain/rock", location="Wadi Qelt at Choziba (~500 m stretch).",
    confirm="L2: an independently identified pre-70 CE outlet; L3: period cut 1.34–1.58 m at its mouth on the side facing the mountain/rock.",
    miss="Outlet mouth zone excavated on that side to ≥1.6 m without a period cut.", inconclusive="Outlet unidentified.",
    evidence=[("Puech 2015 pp. 62, 67–68: wall/parapet/courses or mountain; direction toward, without fixing endpoint.", "via shared/readings.json e32")],
    inference=("If 'mountain', the retaining-wall test no longer discriminates.", "medium"), **c32)

# ---------------------------------------------------------------- entry 35
c35 = dict(entry="35", reading_assumed="ביגר של פי צוק קדרון חפור אמות שלוש", reading_editions=["Milik 1962 D28 p. 268", "Puech 2015 pp. 72–73"],
    reading_status="'gorge' (Milik, Puech) vs 'peak' (Lefkovits); 'cairn' vs 'dam' (Eshel); 'pottery' (Wolters, Pixner) removes the place",
    feature_type="cairn at the mouth of the Kidron gorge", measures=[{"cubits": 3, "edition": "all", "type": "digging depth"}],
    report_extra=["cairn dating evidence", "exact position relative to the canyon entrance/exit", "depth below cairn"], priority="low", scorability="area-level",
    sources=["SWP III pp. 3, 219", "ʿAtiqot 41 (Dahari) pp. 233, 239", "Israel Guide pp. 194–195 (via repo)"])
rec(id="P35-A", branch="gorge mouth reached shortly before Mar Saba on the way from Jerusalem (Milik, Puech)", place_id="mar_saba",
    feature_detail="Cairn at the upper canyon entrance near Mar Saba.", orientation="none", location="Kidron gorge at Deir Mar Saba (gazetteer ~500 m stretch).",
    confirm="L2: a cairn of the period at the canyon entrance; L3: period cut 1.34–1.58 m.", miss="Feature-level only.", inconclusive="Default.",
    evidence=[("Puech: the gorge 'a short distance before it reaches Mar Saba on the way from Jerusalem'.", "Puech 2015 p. 73 via shared/readings.json")],
    inference=("", "low"), **c35)
rec(id="P35-B", branch="gorge mouth = lower canyon outlet where the Kidron leaves the escarpment", place_id=None,
    feature_detail="Dahari describes the Kidron as a canyon also where it leaves the escarpment, with 1st-century use.", orientation="none",
    location="Lower Kidron canyon exit toward the Dead Sea (no gazetteer coordinate).",
    confirm="As P35-A at the lower exit.", miss="Feature-level only.", inconclusive="Default.",
    evidence=[("ʿAtiqot 41 (Dahari) pp. 233, 239.", "via repo phase5_summary §4")], inference=("", "low"), **c35)
rec(id="P35-C", branch="יגר = dam at the start of Hyrcania's southern aqueduct (Eshel)", place_id="hyrcania",
    feature_detail="Dam on the Kidron feeding Hyrcania's 9 km southern (Herodian) aqueduct.", orientation="none", location="Kidron intake of Hyrcania's S aqueduct.",
    confirm="L2: dam dated before 70 CE; L3: period cut 1.34–1.58 m in/under the dam.", miss="Dam dated only after 135 CE.", inconclusive="Default.",
    evidence=[("Eshel CSS pp. 101–102; S aqueduct = 9 km Qidron line (Herodian).", "via shared/readings.json and repo site_identification_review.md")],
    inference=("Fortress abandonment after Herod (Patrich) weakens 1st-c. CE use.", "low"), **c35)

# ---------------------------------------------------------------- entry 36/37
rec(id="P36-A", entry="36", branch="Shaveh = King's Valley / Kidron (Puech, Høgenhaven)",
    reading_assumed="בשלף של השוא הצופא מערב בדרום בצריח הצופא צפון חפור אמות עשרין וארבע", reading_editions=["Puech 2006 p. 194 n. 304; 2015 pp. 73–74", "Høgenhaven 2020 p. 77"],
    reading_status="Shaveh location disputed; Lefkovits allows a place name Shalef", place_id="jer_kidron_mon",
    feature_type="underground chamber facing north, in the southern part of a west-facing fallow tract",
    feature_detail="Rock-cut chamber with a north-facing entrance on the Kidron's west-facing (east-bank) slope.",
    orientation="tract faces west; chamber entrance faces north; chamber in the southern part",
    measures=[{"cubits": 24, "edition": "Puech", "type": "digging depth or distance (unresolved; 10.7–12.6 m is deep for a dig)"}],
    location="Kidron valley at the monuments (~100 m) and slopes south.",
    confirm="L2: a period rock-cut chamber with north-facing entrance in the southern sector of a west-facing slope; L3: period cut at 10.7–12.6 m (distance model: from the entrance along its axis).",
    miss="Feature-level only.", inconclusive="Default.", report_extra=["entrance azimuth", "chamber date", "slope aspect"],
    priority="low", scorability="area-level", evidence=[("Period rock-cut tombs in the Kidron.", "via shared/phase5_archaeology_index.csv (Avni & Greenhut 1996)")],
    inference=("Many north-facing chambers; weak.", "low"), sources=["Avni & Greenhut 1996", "SWP III pp. 53–54"])
rec(id="P36-B", entry="36", branch="Shaveh = Bethso / Baqʿa necropolis SW of Jerusalem (Milik)",
    reading_assumed="as P36-A; ha-Šoʾ = Bethso", reading_editions=["Milik 1962 p. 274"], reading_status="disputed", place_id="jer_baqa",
    feature_type="north-facing chamber on a west-facing uncultivated slope", feature_detail="Milik: the uncultivated west slope of a ravine.",
    orientation="as P36-A", measures=[{"cubits": 24, "edition": "Milik", "type": "unresolved"}], location="el-Baqʿa plain SW of the Old City (~700 m).",
    confirm="As P36-A in the Baqʿa.", miss="Feature-level only.", inconclusive="Default.", report_extra=["entrance azimuth", "date"],
    priority="low", scorability="area-level", evidence=[("Milik: ha-Šoʾ = Josephus's Bethso.", "Milik 1962 p. 274 via shared/readings.json")],
    inference=("'Facing west' is odd for a plain (repo sequence study).", "low"), sources=["Milik DJD III p. 274"])
rec(id="P37-A", entry="37", branch="irrigated part of the Shaveh below Siloam; underground chamber (Puech)",
    reading_assumed="ברוי ('irrigated land', Puech; engraved/shared text בדור) של השוא, בצריח (emended from engraved בצויח) … חפור אמות אחת עסרה", reading_editions=["Puech 2015 p. 74"], reading_status="engraved בצויח emended to בצריח; Milik 'cippus'; Lefkovits place name 'Din'",
    place_id="jer_shaveh", feature_type="underground chamber in irrigated land", feature_detail="Irrigated gardens below Siloam (Kidron–Hinnom).",
    orientation="none", measures=[{"cubits": 11, "edition": "all", "type": "digging depth"}], location="Valley of Shaveh unresolved; Kidron–Hinnom irrigated stretch preferred by water-source argument.",
    confirm="L2: a period chamber within the irrigated zone below Siloam; L3: period cut at 4.9–5.8 m.", miss="Feature-level only.", inconclusive="Default.",
    report_extra=["chamber date and depth", "irrigation context"], priority="low", scorability="area-level",
    evidence=[("Only the Kidron–Hinnom stretch has a reported water source for irrigated land.", "via repo phase5_summary §5 (Wilson 1871 pp. 21–22)")],
    inference=("", "low"), sources=["Wilson 1871 pp. 21–22", "SWP III pp. 53–54"])
rec(id="P37-B", entry="37", branch="cippus (boundary stone) reading (Milik)", reading_assumed="chamber word read as a cippus (boundary stone)", reading_editions=["Milik 1962 p. 274"], reading_status="disputed",
    place_id="jer_shaveh", feature_type="boundary stone in irrigated land", feature_detail="", orientation="none", measures=[{"cubits": 11, "edition": "all", "type": "digging depth"}],
    location="As P37-A.", confirm="L2: an inscribed/period boundary stone in situ; L3: period cut at 4.9–5.8 m beside it.", miss="Feature-level only.", inconclusive="Default.",
    report_extra=["stone in situ?", "inscription"], priority="low", scorability="area-level", evidence=[("Milik: a cippus.", "Milik 1962 p. 274 via shared/readings.json")],
    inference=("", "low"), sources=["Milik DJD III p. 274"])

# ---------------------------------------------------------------- entry 38
c38 = dict(entry="38", place_id="natuf", reading_editions=["Milik 1960 p. 150; 1962 C4–C5", "Puech 2015 pp. 76–78"],
    reading_status="feature word disputed (dovecote / rock opening / tower / drain); IX 2 corrupt (depth vs two holes)",
    measures=[{"cubits": 13, "edition": "all", "type": "horizontal measure from the edge"}, {"cubits": 7, "edition": "Milik (dig 7) — Puech reads two holes, no depth", "type": "digging depth"}],
    report_extra=["position of the spring emergence (edge)", "rock-cut niches/columbarium or regular openings within ~10 m, with dating", "distance from the edge to each candidate"],
    priority="medium", scorability="feature-level", sources=["SWP III pp. 357–376", "Milik 1960 p. 150", "Milik DJD III C4"])
rec(id="P38-A", branch="dovecote cut into the rock at the spring (Puech)", reading_assumed="בשובך שבשולי הנטף משח משוליו אמות שלוש עשרא (Puech: 'dovecote'; IX 2 read as two holes/pits, no depth)",
    feature_type="rock-cut dovecote (columbarium) at the spring emergence; two holes", feature_detail="Dovecote at the edge of ʿAin en-Naṭuf; deposit 13 cubits from its edge, in two holes.",
    orientation="none", location="ʿAin en-Naṭuf, Wadi Khareitun (gazetteer ~700 m).",
    confirm="L2: a rock-cut columbarium of the period at the spring; L3: two period cuts 5.8–6.8 m (13 c.) from its edge.",
    miss="Spring margin surveyed with no rock-cut columbarium of any period.", inconclusive="Undated niches.",
    evidence=[("No dovecote or rock opening reported at the spring.", "via shared/readings.json e38"), ("Dovecotes in the district only in texts.", "via shared/phase5_archaeology_index.csv")],
    inference=("A survey can test this cheaply.", "medium"), **c38)
rec(id="P38-B", branch="regular cave/rock opening at the spring emergence (Milik)", reading_assumed="שובך = regular opening of a cave/rock face; dig 7",
    feature_type="regular opening in the rock face at the spring", feature_detail="", orientation="none", location="As P38-A.",
    confirm="L2: a period rock opening at the spring; L3: period cut at 3.1–3.7 m, 5.8–6.8 m from the edge.", miss="Feature-level only.", inconclusive="Default.",
    evidence=[("Milik: a regular opening of a cave or rock face.", "Milik 1962 C4 pp. 238–239 via shared/readings.json")], inference=("", "low"), **c38)
