#!/usr/bin/env python3
"""Build the Google Drive navigation tree for the Copper Scroll library.

Run it where the Drive folder is mounted (the Mac, or the linked Linux VM):

    python3 tools/drive_navtree.py "<...>/My Drive/Copper Scroll" --out-dir research/sources

It writes two files:
  drive_manifest.csv  one row per folder and file: path, Drive ID, bytes, former name
  drive_index.md      the same tree as a readable page with Drive links

Drive IDs come from the Google Drive for desktop extended attribute
`com.google.drivefs.item-id#S`, so no Drive API call is needed. Former names are
kept from the previous manifest (matched by Drive ID) and from any reorganization
log given with --log (tab-separated: drive_id, old_path, new_path, bytes).
"""
import argparse
import csv
import os
import subprocess
import sys

ATTR = "com.google.drivefs.item-id#S"
SKIP = {"00 drive_manifest.csv", "00 START HERE – Drive index.md", "Icon\r"}


def drive_id(path):
    try:
        return os.getxattr(path, ATTR).decode()
    except AttributeError:  # macOS Python has no os.getxattr
        r = subprocess.run(["xattr", "-p", ATTR, path], capture_output=True, text=True)
        return r.stdout.strip() if r.returncode == 0 else ""
    except OSError:
        return ""


def human(n):
    n = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1000 or unit == "GB":
            return f"{n:.0f} {unit}" if unit in ("B", "KB") else f"{n:.1f} {unit}"
        n /= 1000


def link(i, folder):
    if not i:
        return ""
    return f"https://drive.google.com/drive/folders/{i}" if folder else f"https://drive.google.com/file/d/{i}/view"


def walk(root):
    rows = []
    for cur, dirs, files in os.walk(root):
        dirs[:] = sorted(d for d in dirs if not d.startswith("."))
        rel = os.path.relpath(cur, root)
        for d in dirs:
            p = os.path.normpath(os.path.join(rel, d))
            rows.append({"path": p, "drive_id": drive_id(os.path.join(root, p)), "bytes_or_folder": "folder"})
        for f in sorted(files):
            if f.startswith(".") or f in SKIP:
                continue
            p = os.path.normpath(os.path.join(rel, f))
            full = os.path.join(root, p)
            rows.append({"path": p, "drive_id": drive_id(full), "bytes_or_folder": str(os.path.getsize(full))})
    rows.sort(key=lambda r: r["path"])
    return rows


INTRO = """# Copper Scroll library in Google Drive

Generated by `tools/drive_navtree.py` from the Drive folder **My Drive/Copper Scroll** ({root_link}).
{n_files} files in {n_folders} folders, {total}. Last built {date}.

## How to use this index

- **Find a file:** search this page, or `drive_manifest.csv`, by author, year, journal or site.
- **Open it in a session:** use the Drive ID with the Drive connector (`get_file_metadata`, `read_file_content`, `download_file_content`), or search `parentId = '<folder ID>'` to list one folder.
- **Old file names:** repo notes before 9 Oct 2026 cite the original download names (for example `screencapture-jstor-org-stable-27930608-…pdf` or `10.2307@23456536.pdf`). Look up the old name in the `former_name` column of `drive_manifest.csv`. Drive IDs did not change, so old Drive links still work.
- **On the Mac:** the same tree is at `~/Library/CloudStorage/GoogleDrive-alexkesin@gmail.com/My Drive/Copper Scroll/`. Most files are cloud-only until opened.
- **Rebuild after changes:** run `python3 tools/drive_navtree.py "<that path>" --out-dir research/sources --previous research/sources/drive_manifest.csv` and commit both files. Add `--drive-names --out-dir "<that path>"` to refresh the copies in the Drive root (`00 START HERE – Drive index.md`, `00 drive_manifest.csv`).

## Naming rules

- Books, articles and chapters: `Author Year – Short title (Journal volume).ext`. Editors are marked `ed.` or `eds`.
- Series volumes keep their series label: `ESI 05 (1986)`, `HA 40 (1971)`, `CIIP I.1 – …`, `CPJ 2 – …`, `TAO 3`.
- `[JSTOR capture]` / `[screen capture]` = a browser capture of page images, not the publisher PDF.
- `(compressed)`, `(extract)`, `(OCR)`, `copy A/B`, `(small pdf)`, `(epub)` = other copies of the same work. Keep the full copy for citation; the smaller copies fit upload limits.
- Satellite products keep their USGS entity names (for example `D3C1208-400636A015.tgz`, `DS1101-2168DF040_40.tgz`); the folder name gives the mission and date.
- `99 Duplicates – review before deleting` holds byte-identical or near-identical copies. Nothing there is unique.

## Folders

| Folder | Files (all levels) | Drive |
|---|---:|---|
{folder_table}
"""


def build_md(rows, root_id, date):
    folders = [r for r in rows if r["bytes_or_folder"] == "folder"]
    files = [r for r in rows if r["bytes_or_folder"] != "folder"]
    total = sum(int(r["bytes_or_folder"]) for r in files)

    def count(prefix):
        return sum(1 for r in files if r["path"].startswith(prefix + os.sep))

    table = "\n".join(
        f"| {'&nbsp;&nbsp;&nbsp;' * r['path'].count(os.sep)}{os.path.basename(r['path'])} | {count(r['path'])} | [{r['drive_id']}]({link(r['drive_id'], True)}) |"
        for r in folders
    )
    out = [INTRO.format(root_link=f"[{root_id}]({link(root_id, True)})", n_files=len(files), n_folders=len(folders),
                        total=human(total), date=date, folder_table=table)]
    by_parent = {}
    for r in files:
        by_parent.setdefault(os.path.dirname(r["path"]), []).append(r)
    out.append("## Files by folder\n")
    for parent in sorted(by_parent):
        title = parent or "(root)"
        out.append(f"### {title}\n")
        out.append("| File | Size | Drive ID |\n|---|---:|---|")
        for r in by_parent[parent]:
            name = os.path.basename(r["path"]).replace("|", "\\|")
            out.append(f"| {name} | {human(r['bytes_or_folder'])} | [{r['drive_id']}]({link(r['drive_id'], False)}) |")
        out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("--out-dir", default=".")
    ap.add_argument("--previous", help="earlier drive_manifest.csv, to keep former names")
    ap.add_argument("--log", action="append", default=[], help="reorganization log TSV")
    ap.add_argument("--date", default=None)
    ap.add_argument("--drive-names", action="store_true",
                    help="write '00 drive_manifest.csv' and '00 START HERE – Drive index.md' (names used in the Drive root)")
    a = ap.parse_args()

    former = {}
    if a.previous and os.path.exists(a.previous):
        for r in csv.DictReader(open(a.previous, encoding="utf-8")):
            if r.get("former_name"):
                former[r["drive_id"]] = r["former_name"]
    for log in a.log:
        with open(log, encoding="utf-8") as fh:
            next(fh)
            for line in fh:
                i, old, new, _ = line.rstrip("\n").split("\t")
                if os.path.basename(old) != os.path.basename(new):
                    former.setdefault(i, os.path.basename(old))

    rows = walk(a.root)
    for r in rows:
        r["former_name"] = former.get(r["drive_id"], "")
    missing = [r["path"] for r in rows if not r["drive_id"]]
    if missing:
        print("warning: no Drive ID yet (not synced?):", *missing, sep="\n  ", file=sys.stderr)

    os.makedirs(a.out_dir, exist_ok=True)
    csv_name, md_name = ("00 drive_manifest.csv", "00 START HERE – Drive index.md") if a.drive_names else ("drive_manifest.csv", "drive_index.md")
    with open(os.path.join(a.out_dir, csv_name), "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["path", "drive_id", "bytes_or_folder", "former_name"])
        w.writeheader()
        w.writerows(rows)
    import datetime
    date = a.date or datetime.date.today().isoformat()
    with open(os.path.join(a.out_dir, md_name), "w", encoding="utf-8") as fh:
        fh.write(build_md(rows, drive_id(a.root), date))
    print(f"{len(rows)} rows written to {a.out_dir}")


if __name__ == "__main__":
    main()
